var _yt_www={};(function(m){var window=this;var qa,ra;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.da=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.p=function(a,b){for(var c=a.split("."),d=b||m.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.fa=function(){};m.ga=function(a){a.getInstance=function(){return a.$b?a.$b:a.$b=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ja=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ka=function(a){return"string"==typeof a};m.ma=function(a){return"number"==typeof a};m.na=function(a){return"function"==m.ha(a)};m.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.pa=function(a){return a[qa]||(a[qa]=++ra)};
var sa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?sa:ta;return m.q.apply(null,arguments)};
m.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};var ua=function(a){ua[" "](a);return a};m.va=function(a,b){try{return ua(a[b]),!0}catch(c){}return!1};
m.wa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.wa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.xa=function(a,b){return 0==a.lastIndexOf(b,0)};m.ya=function(a){return(0,window.encodeURIComponent)(String(a))};
m.za=function(a){if(!Aa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ba,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ca,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Da,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ea,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Fa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ga,"&#0;"));return a};m.Ha=function(a,b){return-1!=a.indexOf(b)};m.Ia=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
m.Ja=function(a,b){for(var c=0,d=(0,m.Ka)(String(a)).split("."),e=(0,m.Ka)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",n=e[h]||"",v=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var J=v.exec(k)||["","",""],Q=w.exec(n)||["","",""];if(0==J[0].length&&0==Q[0].length)break;c=La(0==J[1].length?0:(0,window.parseInt)(J[1],10),0==Q[1].length?0:(0,window.parseInt)(Q[1],10))||La(0==J[2].length,0==Q[2].length)||La(J[2],Q[2])}while(0==c)}return c};
var La=function(a,b){return a<b?-1:a>b?1:0};var Ma=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};m.Na=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Oa=function(a){var b=m.ka(void 0)?m.Ia(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Pa=function(a,b,c){b=m.Qa(a,b,c);return 0>b?null:m.ka(a)?a.charAt(b):a[b]};
m.Qa=function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};m.Sa=function(a,b){return 0<=(0,m.Ta)(a,b)};m.Ua=function(a,b){var c=(0,m.Ta)(a,b),d;(d=0<=c)&&m.Va(a,c);return d};m.Va=function(a,b){return 1==m.Wa.splice.call(a,b,1).length};m.Xa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.u=function(){this.Vb=this.Vb;this.rb=this.rb};m.Ya=function(a,b){m.Za(a,m.r(m.$a,b))};
m.Za=function(a,b){a.Vb?b.call(void 0):(a.rb||(a.rb=[]),a.rb.push(m.da(void 0)?(0,m.q)(b,void 0):b))};m.$a=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.ab=function(){m.u.call(this);this.n=1;this.k=[];this.l=0;this.j=[];this.Sc={}};m.bb=function(a){cb(m.db,arguments)};m.x=function(a,b){return a in m.db?m.db[a]:b};m.y=function(a,b){m.na(a)&&(a=m.eb(a));return window.setTimeout(a,b)};m.fb=function(a,b){m.na(a)&&(a=m.eb(a));return window.setInterval(a,b)};m.gb=function(a){window.clearTimeout(a)};
m.hb=function(a){window.clearInterval(a)};m.eb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.ib(b),b;}}:a};m.ib=function(a,b){var c=m.p("yt.www.errors.log");c?c(a,b):(c=m.x("ERRORS")||[],c.push([a,b]),m.bb("ERRORS",c))};m.jb=function(a){return a in m.kb};m.lb=function(a,b,c){var d=b||{};if(a=a in m.kb?m.kb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};
var cb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.z=function(a,b,c){var d=mb();if(d){var e=d.subscribe(a,function(){if(!nb||nb!=e){var d=arguments,h=function(){pb[e]&&b.apply(c||window,d)};try{qb[a]?h():m.y(h,0)}catch(k){m.ib(k)}}},c);pb[e]=!0;rb[a]||(rb[a]=[]);rb[a].push(e);return e}return 0};m.sb=function(a){var b=mb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.A)(a,function(a){b.unsubscribeByKey(a);delete pb[a]}))};
m.B=function(a,b){var c=mb();return c?c.publish.apply(c,arguments):!1};m.tb=function(a,b){qb[a]=!0;var c=mb(),c=c?c.publish.apply(c,arguments):!1;qb[a]=!1;return c};var mb=function(){return m.p("yt.pubsub.instance_")};m.ub=function(){return!!m.p("yt.scheduler.instance")};m.vb=function(a,b){void 0===b&&(b=window.NaN);var c=m.p("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.y(a,b||0)};m.wb=function(a,b){return m.vb(a,b)};
m.xb=function(a){var b=m.p("yt.scheduler.instance.cancelJob");b?b(a):m.gb(a)};m.yb=function(a){for(var b=0,c=a.length;b<c;b++)m.xb(a[b])};m.zb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.B=d?m.eb(d):null;this.A=e?m.eb(e):null;this.n=[];this.j=this.k=0};m.Ab=function(a){m.xb(a.k);a.k=m.wb((0,m.q)(a.init,a))};
m.Bb=function(a){a.name in Cb&&Db(a.name);Cb[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.A)(a.deps,function(b){if(!(b in Cb))throw Error("Module "+b+" required by "+a.name);Cb[b].reqs.push(a.name)});a.enable()};var Db=function(a){if(a in Cb){var b=Cb[a];(0,m.A)(b.reqs,function(a){Db(a)});try{b.disable()}catch(c){}delete Cb[a]}};m.Eb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.Fb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
m.Gb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.Hb=function(a,b){b in a&&delete a[b]};m.Ib=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};m.Jb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.Kb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Lb.length;f++)c=Lb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Mb=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return Mb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};m.Nb=function(){this.j="";this.k=Ob};m.Pb=function(a){return a instanceof m.Nb&&a.constructor===m.Nb&&a.k===Ob?a.j:"type_error:Const"};m.Qb=function(){this.j="";this.k=Rb};m.Sb=function(a){return a instanceof m.Qb&&a.constructor===m.Qb&&a.k===Rb?a.j:"type_error:SafeStyle"};m.Tb=function(a){var b=new m.Qb;b.j=a;return b};
m.Ub=function(){this.j="";this.k=Vb};m.Wb=function(a){return a instanceof m.Ub&&a.constructor===m.Ub&&a.k===Vb?a.j:"type_error:SafeUrl"};m.Xb=function(a){if(a instanceof m.Ub)return a;a=a.jf?a.ve():String(a);a=Yb.test(a)?Zb(a):"about:invalid#zClosurez";var b=new m.Ub;b.j=a;return b};var Zb=function(a){try{var b=(0,window.encodeURI)(a)}catch(c){return"about:invalid#zClosurez"}return b.replace($b,function(a){return ac[a]})};var bc=function(){this.j=cc};m.dc=function(){this.j="";this.l=ec;this.k=null};
m.fc=function(a){return a instanceof m.dc&&a.constructor===m.dc&&a.l===ec?a.j:"type_error:SafeHtml"};m.gc=function(a,b,c){if(!hc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in ic)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return m.jc(a,b,c)};
m.kc=function(a){function b(a){if(m.ia(a))(0,m.A)(a,b);else{var f;a instanceof m.dc?f=a:(f=null,a.cl&&(f=a.Vg()),a=m.za(a.jf?a.ve():String(a)),f=m.lc(a,f));d+=m.fc(f);f=f.Vg();0==c?c=f:0!=f&&c!=f&&(c=null)}}var c=0,d="";(0,m.A)(arguments,b);return m.lc(d,c)};m.lc=function(a,b){var c=new m.dc;c.j=a;c.k=b;return c};
m.jc=function(a,b,c){var d=null,e="<"+a;if(b)for(var f in b){if(!hc.test(f))throw Error('Invalid attribute name "'+f+'".');var h=b[f];if(null!=h){var k,n=a;k=f;if(h instanceof m.Nb)h=m.Pb(h);else if("style"==k.toLowerCase()){if(!m.oa(h))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof h+" given: "+h);if(!(h instanceof m.Qb)){var n="",v=void 0;for(v in h){if(!/^[-_a-zA-Z0-9]+$/.test(v))throw Error("Name allows only [-_a-zA-Z0-9], got: "+v);var w=
h[v];if(null!=w){if(w instanceof m.Nb)w=m.Pb(w);else if(mc.test(w)){for(var J=!0,Q=!0,ca=0;ca<w.length;ca++){var la=w.charAt(ca);"'"==la&&Q?J=!J:'"'==la&&J&&(Q=!Q)}J&&Q||(w="zClosurez")}else w="zClosurez";n+=v+":"+w+";"}}h=n?m.Tb(n):nc}h=m.Sb(h)}else{if(/^on/i.test(k))throw Error('Attribute "'+k+'" requires goog.string.Const value, "'+h+'" given.');if(k.toLowerCase()in oc)if(h instanceof bc)h=h instanceof bc&&h.constructor===bc&&h.j===cc?"":"type_error:TrustedResourceUrl";else if(h instanceof m.Ub)h=
m.Wb(h);else throw Error('Attribute "'+k+'" on tag "'+n+'" requires goog.html.SafeUrl or goog.string.Const value, "'+h+'" given.');}h.jf&&(h=h.ve());k=k+'="'+m.za(String(h))+'"';e=e+(" "+k)}}null!=c?m.ia(c)||(c=[c]):c=[];!0===pc[a.toLowerCase()]?e+=">":(d=m.kc(c),e+=">"+m.fc(d)+"</"+a+">",d=d.Vg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return m.lc(e,d)};m.qc=function(a,b){a.innerHTML=m.fc(b)};m.C=function(a,b){return a?a.dataset?a.dataset[m.rc(b)]:a.getAttribute("data-"+b):null};
m.sc=function(a,b){return a?a.dataset?m.rc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.rc=function(a){return tc[a]||(tc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.uc=function(a,b){var c=m.vc(a);window.spf.script.load(a,c,b)};
m.vc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(wc,""),b=b.replace(xc,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};m.yc=function(a,b,c){return Math.min(Math.max(a,b),c)};m.zc=function(a,b){this.x=m.da(a)?a:0;this.y=m.da(b)?b:0};m.Ac=function(a){return m.Ha(m.Bc,a)};var Cc=function(){return m.Ac("Opera")||m.Ac("OPR")};var Dc=function(){return m.Ac("Edge")||m.Ac("Trident")||m.Ac("MSIE")};
var Ec=function(){return(m.Ac("Chrome")||m.Ac("CriOS"))&&!Cc()&&!Dc()};var Fc=function(){return m.Ac("Edge")};m.Gc=function(){return m.Ac("iPhone")&&!m.Ac("iPod")&&!m.Ac("iPad")};var Hc=function(){var a=m.Bc;if(m.Ic)return/rv\:([^\);]+)(\)|;)/.exec(a);if(m.D&&Fc())return/Edge\/([\d\.]+)/.exec(a);if(m.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(m.Jc)return/WebKit\/(\S+)/.exec(a)};var Kc=function(){var a=m.ea.document;return a?a.documentMode:void 0};
m.Lc=function(a){return Mc[a]||(Mc[a]=0<=m.Ja(Nc,a))};m.Oc=function(a){return m.D&&(Fc()||m.Pc>=a)};m.E=function(a){return m.ka(a)?window.document.getElementById(a):a};m.Qc=function(a){return m.ka(a)?window.document.getElementById(a):a};m.F=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Rc("*",a,b)[0];return d||null};
m.Rc=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&m.Sa(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.Sc=function(a,b){m.Eb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Tc?a.setAttribute(Tc[d],b):m.xa(d,"aria-")||m.xa(d,"data-")?a.setAttribute(d,b):a[d]=b})};m.Uc=function(a){var b=m.Vc(a);a=a.parentWindow||a.defaultView;return m.D&&m.Lc("10")&&a.pageYOffset!=b.scrollTop?new m.zc(b.scrollLeft,b.scrollTop):new m.zc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};m.Vc=function(a){return!m.Jc&&m.Wc(a)?a.documentElement:a.body||a.documentElement};
m.Xc=function(a,b,c){return m.Yc(window.document,arguments)};m.Yc=function(a,b){var c=b[0],d=b[1];if(!Zc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.za(d.name),'"');if(d.type){c.push(' type="',m.za(d.type),'"');var e={};m.Kb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ka(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.Sc(c,d));2<b.length&&m.$c(a,c,b,2);return c};
m.$c=function(a,b,c,d){function e(c){c&&b.appendChild(m.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!m.ja(f)||m.oa(f)&&0<f.nodeType?e(f):(0,m.A)(ad(f)?m.Xa(f):f,e)}};m.Wc=function(a){return"CSS1Compat"==a.compatMode};m.bd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.cd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};m.dd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
var ed=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};var fd=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
m.gd=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};m.hd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var ad=function(a){if(a&&"number"==typeof a.length){if(m.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.na(a))return"function"==typeof a.item}return!1};
m.id=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};m.jd=function(a){return function(){return a}};m.kd=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.ld=function(){};
m.md=function(a){if(a instanceof m.ld)return a;if("function"==typeof a.Ob)return a.Ob(!1);if(m.ja(a)){var b=0,c=new m.ld;c.next=function(){for(;;){if(b>=a.length)throw m.nd;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};m.od=function(a,b,c){if(m.ja(a))try{(0,m.A)(a,b,c)}catch(d){if(d!==m.nd)throw d;}else{a=m.md(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.nd)throw e;}}};
m.pd=function(a){if(m.ja(a))return m.Xa(a);a=m.md(a);var b=[];m.od(a,function(a){b.push(a)});return b};m.qd=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};m.rd=function(a){if(sd){sd=!1;var b=m.ea.location;if(b){var c=b.href;if(c&&(c=m.td(c))&&c!=b.hostname)throw sd=!0,Error();}}return a.match(ud)};m.vd=function(a){return a?(0,window.decodeURI)(a):a};m.td=function(a){return m.vd(m.rd(a)[3]||null)};
m.wd=function(a){a=m.rd(a);return m.qd(null,null,null,null,a[5],a[6],a[7])};m.xd=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};m.yd=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.yd(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.ya(b))};var zd=function(a,b){for(var c in b)m.yd(c,b[c],a);return a};m.Ad=function(a){a=zd([],a);a[0]="";return a.join("")};
m.Bd=function(a,b){return m.xd(zd([a],b))};m.Cd=function(a,b,c){a&&(c?a&&(a=m.Xc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.hd(a).body.appendChild(a)):Ed(a,b))};var Ed=function(a,b){var c=new window.Image,d=""+Fd++;Gd[d]=c;c.onload=c.onerror=function(){b&&Gd[d]&&b();delete Gd[d]};c.src=a;c=eval("null")};m.Hd=function(a,b){this.version=a;this.args=b};m.Id=function(a,b){this.j=a;this.Ue=b};
m.Jd=function(a,b){var c=m.Kd();return c?c.publish.call(c,a.toString(),a,b):!1};m.Kd=function(){return m.p("yt.pubsub2.instance_")};var Ld=function(a){m.Hd.call(this,1,arguments)};m.Md=function(a,b,c){Nd(c)[a]=b||(0,m.G)();b||Od(a);m.x("CSI_LOG_ON_TICK")&&Pd(!1,c)};var Qd=function(a,b){Rd(void 0).yt_sts=a;m.Md("_start",b,void 0)};var Sd=function(a){Td(a);Ud();m.l("yt.timing.pingSent_",!1,void 0)};
var Vd=function(a){a=Nd(a);if(a.aft)return a.aft;for(var b=m.x("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
var Wd=function(a,b){var c=Xd(b).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};var Yd=function(a){return Math.round(Zd.timing.navigationStart+a)};
var $d=function(a){var b=window.location.protocol,c=Zd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Yd(d.startTime),a.wfce=Yd(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Yd(c.startTime),a.wffe=Yd(c.responseEnd))};
var ae=function(a){var b=Nd(a),c=Xd(a).span,d=Rd(a),e=m.p("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))be(e),Sd(a)}else{e={v:2,s:m.x("CSI_SERVICE_NAME","youtube"),action:m.x("TIMING_ACTION")};if(Zd.now&&Zd.timing){var f=Zd.timing.navigationStart+Zd.now(),f=Math.round((0,m.G)()-f);d.yt_hrd=f}var f=m.x("TIMING_INFO")||{},h;for(h in f)d[h]=f[h];h=d.srt;delete d.srt;var k;h||0===h||(k=Zd.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=
h;d.h5jse&&(f=window.location.protocol+m.p("ytplayer.config.assets.js"),(f=Zd.getEntriesByName?Zd.getEntriesByName(f)[0]:null)?d.h5jse=Math.round(d.h5jse-f.responseEnd):delete d.h5jse);b.aft=Vd(a);f=b._start;if("cold"==d.yt_lt){k||(k=Zd.timing||{});var n;a:if(n=k,n.msFirstPaint)n=Math.max(0,n.msFirstPaint);else{var v=window.chrome;if(v&&(v=v.loadTimes,m.na(v))){var v=v(),w=1E3*Math.min(v.requestTime||window.Infinity,v.startLoadTime||window.Infinity),w=window.Infinity===w?0:n.navigationStart-w;n=Math.max(0,
Math.round(1E3*v.firstPaintTime+w)||0);break a}n=0}0<n&&n>f&&(b.fpt=n);Wd(k,a);m.x("EXP_WEBFONT_ENABLED")&&Zd.getEntriesByType&&$d(b)}d.p=m.x("CLIENT_PROTOCOL")||"unknown";d.t=m.x("CLIENT_TRANSPORT")||"unknown";m.x("EXP_CSI_BEACON_API")&&window.navigator.sendBeacon&&(d.ba=1);for(var J in d)"_"!=J.charAt(0)&&(e[J]=d[J]);m.x("CSI_MORE")&&(b.ps=(0,m.G)());d={};k=[];for(var Q in b)"_"!=Q.charAt(0)&&(n=Math.max(Math.round(b[Q]-f),0),d[Q]=n,k.push(Q+"."+n));e.rt=k.join(",");b={};Q=[];for(var ca in c)"_"!=
ca.charAt(0)&&(b[ca]=c[ca],Q.push(ca+"."+c[ca]));e.it=Q.join(",");(c=m.p("ytdebug.logTiming"))&&c(e,d,b);Sd(a);m.x("EXP_DEFER_CSI_PING")?(ce(),m.l("yt.timing.deferredPingArgs_",e,void 0),a=m.y(ce,0),m.l("yt.timing.deferredPingTimer_",a,void 0)):be(e);m.Jd(de,new Ld(d.aft+(h||0)))}};
var Pd=function(a,b){var c=m.x("TIMING_ACTION"),d=Nd(b),e=!0;m.x("CSI_LOG_ON_TICK")&&(e=!!m.p("yt.timing.ready_"));if(e&&c&&d._start&&Vd(b)){c=!0;e=m.x("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,h=e.length;f<h;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&ae(b)}};var ee=function(a){m.x("CSI_LOG_ON_TICK")||Pd(!1,a)};
var be=function(a){m.x("EXP_DEFER_CSI_PING")&&(m.gb(m.p("yt.timing.deferredPingTimer_")),m.l("yt.timing.deferredPingArgs_",null,void 0));var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];a=b+"?"+c.substring(1);m.x("EXP_CSI_BEACON_API")&&window.navigator.sendBeacon?window.navigator.sendBeacon&&window.navigator.sendBeacon(a)||m.Cd(a,void 0):m.Cd(a);m.l("yt.timing.pingSent_",!0,void 0)};
var ce=function(a){if(m.x("EXP_DEFER_CSI_PING")){var b=m.p("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),be(b))}};var Nd=function(a){return Xd(a).tick};var Rd=function(a){return Xd(a).info};var Xd=function(a){return m.p("ytcsi."+(a||"")+"data_")||Td(a)};var Td=function(a){var b={tick:{},span:{},info:{}};m.l("ytcsi."+(a||"")+"data_",b,void 0);return b};var fe=function(a){m.x("CSI_MORE")&&!m.p("yt.timing.pingSent_")&&(Rd(void 0).ap=1,Rd(void 0).yt_fss=a,ae())};
var ge=function(a){a=m.he(a);return m.ie(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};m.ie=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};m.he=function(a){a=(0,m.je)(a);return null===a?null:a.split(".").reverse()};m.ke=function(a,b){m.Cd("/gen_204?"+a,b)};m.le=function(a){if(a.classList)return a.classList;a=a.className;return m.ka(a)&&a.match(/\S+/g)||[]};
m.H=function(a,b){return a.classList?a.classList.contains(b):m.Sa(m.le(a),b)};m.I=function(a,b){a.classList?a.classList.add(b):m.H(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.K=function(a,b){a.classList?a.classList.remove(b):m.H(a,b)&&(a.className=(0,m.me)(m.le(a),function(a){return a!=b}).join(" "))};m.ne=function(a,b,c){c?m.I(a,b):m.K(a,b)};
var oe=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.Jb(pe);this.assets=a.assets||{};this.attrs=a.attrs||m.Jb(qe);this.params=a.params||m.Jb(re);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};m.se=function(a){a instanceof oe||(a=new oe(a));return a};var te=function(){return null!=m.ue};
m.ve=function(){return m.ue?m.ue.invoke():null};m.we=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.A)(a.childNodes,function(a){b.appendChild(m.we(a))}):b.innerHTML=a.innerHTML;return b};
m.xe=function(a){if(a=a||window.event){for(var b in a)b in ye||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.hb=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Ol=a.pageX;this.Pl=a.pageY}};m.ze=function(a,b,c,d){return m.Gb(m.Ae,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.L=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.ze(a,b,c,d);if(e)return e;var e=++Be.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.xe(d);if(!m.id(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.xe(b);b.currentTarget=a;return c.call(a,b)};h=m.eb(h);m.Ae[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",
h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.M=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.A)(a,function(a){if(a in m.Ae){var c=m.Ae[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete m.Ae[a]}}))};
m.Ce=function(a){a=a||window.event;a=a.target||a.srcElement;3==a.nodeType&&(a=a.parentNode);return a};m.De=function(a){this.j=a};m.Ee=function(a){a=(a.j.cookie||"").split(m.Fe);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};m.Ge=function(a,b,c,d){m.He.set(""+a,b,c,"/",d||"youtube.com")};m.Ie=function(a,b){return m.He.get(""+a,b)};
m.Je=function(a,b){a=!!a;m.l("_lactCookie",a,window);if(null==m.p("_lact",window)){if(m.x("EXP_LACT_TEMPDATA")){var c=(0,window.parseInt)(m.x("LACT"),10),c=(0,window.isFinite)(c)?(0,m.G)()-Math.max(c,0):-1;m.l("_lact",c,window);-1==c&&Ke()}else a&&b?(c=m.Ie("ACTIVITY","-1"),m.l("_lact",(0,window.parseInt)(c,10),window)):(m.l("_lact",-1,window),Ke());m.L(window.document,"keydown",Ke);m.L(window.document,"keyup",Ke);m.L(window.document,"mousedown",Ke);m.L(window.document,"mouseup",Ke);m.x("EXP_LACT_MOUSE")&&
m.z("page-mouse",Ke);m.x("EXP_LACT_SCROLL")&&m.z("page-scroll",Ke);m.x("EXP_LACT_RESIZE")&&m.z("page-resize",Ke)}};var Ke=function(){var a=m.p("_lact",window);null==a&&(m.Je(),a=m.p("_lact",window));var b=(0,m.G)();m.l("_lact",b,window);m.x("EXP_LACT_TEMPDATA")||m.p("_lactCookie",window)&&1E3<=b-a&&m.Ge("ACTIVITY",""+b,-1);m.B("USER_ACTIVE")};m.Le=function(){var a=m.p("_lact",window);return null==a?-1:Math.max((0,m.G)()-a,0)};
m.Me=function(a,b,c){var d=m.td(a);if(d==m.td(window.location.href)||!d&&m.xa(a,"/"))if(a=m.wd(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&Ne(a,b,c)):Ne(a,b)};var Ne=function(a,b,c){a=m.x("SMALLER_SESSION_TEMPDATA_NAME")?"ST-"+Ma(a).toString(36):"s_tempdata-"+Ma(a);c=c||5;b=b?m.Ad(b):"";m.Ge(a,b,c)};m.Oe=function(a,b,c){var d=c||"";c=window.location;a=m.Bd(a,b||{})+d;a=a instanceof m.Ub?a:m.Xb(a);c.href=m.Wb(a)};
m.Pe=function(a,b){b&&m.Me(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):m.Oe(a)};m.Qe=function(a,b,c){var d=m.x("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.Me(a,b);if(c)return!1;m.Pe(a);return!0};var Re=function(a,b,c){this.A=c;this.l=a;this.n=b;this.k=0;this.j=null};var Se=function(a){m.ea.setTimeout(function(){throw a;},0)};
var Te=function(){var a=m.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!m.Ac("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Dc()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.da(c.next)){c=c.next;var a=c.Hn;c.Hn=null;a()}};return function(a){d.next={Hn:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.ea.setTimeout(a,0)}};var Ue=function(){this.k=this.j=null};var Ve=function(){this.next=this.scope=this.Yd=null};var We=function(a,b){Xe||Ye();Ze||(Xe(),Ze=!0);$e.add(a,b)};
var Ye=function(){if(m.ea.Promise&&m.ea.Promise.resolve){var a=m.ea.Promise.resolve();Xe=function(){a.then(af)}}else Xe=function(){var a=af;!m.na(m.ea.setImmediate)||m.ea.Window&&m.ea.Window.prototype&&m.ea.Window.prototype.setImmediate==m.ea.setImmediate?(bf||(bf=Te()),bf(a)):m.ea.setImmediate(a)}};var af=function(){for(var a=null;a=$e.remove();){try{a.Yd.call(a.scope)}catch(b){Se(b)}cf.put(a)}Ze=!1};m.df=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
m.ef=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.ff=function(a,b){this.j=0;this.C=void 0;this.n=this.k=this.l=null;this.A=this.B=!1;if(a==m.gf)hf(this,2,b);else try{var c=this;a.call(b,function(a){hf(c,2,a)},function(a){hf(c,3,a)})}catch(d){hf(this,3,d)}};var jf=function(){this.next=this.context=this.k=this.l=this.j=null;this.n=!1};var kf=function(a,b,c){var d=lf.get();d.l=a;d.k=b;d.context=c;return d};m.gf=function(){};
m.mf=function(a,b,c,d){a instanceof m.ff?nf(a,kf(b||m.fa,c||null,d)):a.then(b,c,d)};var of=function(a,b){if(0==a.j)if(a.l){var c=a.l;if(c.k){for(var d=0,e=null,f=null,h=c.k;h&&(h.n||(d++,h.j==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.j&&1==d?of(c,b):(f?(d=f,d.next==c.n&&(c.n=d),d.next=d.next.next):pf(c),qf(c,e,3,b)))}a.l=null}else hf(a,3,b)};var nf=function(a,b){a.k||2!=a.j&&3!=a.j||rf(a);a.n?a.n.next=b:a.k=b;a.n=b};
m.sf=function(a,b,c,d){var e=kf(null,null,null);e.j=new m.ff(function(a,h){e.l=b?function(c){try{var e=b.call(d,c);a(e)}catch(v){h(v)}}:a;e.k=c?function(b){try{var e=c.call(d,b);!m.da(e)&&b instanceof tf?h(b):a(e)}catch(v){h(v)}}:h});e.j.l=a;nf(a,e);return e.j};
var hf=function(a,b,c){if(0==a.j){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.ef(c)){a.j=1;m.mf(c,a.G,a.L,a);return}if(m.oa(c))try{var d=c.then;if(m.na(d)){uf(a,c,d);return}}catch(e){b=3,c=e}}a.C=c;a.j=b;a.l=null;rf(a);3!=b||c instanceof tf||vf(a,c)}};var uf=function(a,b,c){function d(b){f||(f=!0,a.L(b))}function e(b){f||(f=!0,a.G(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}};var rf=function(a){a.B||(a.B=!0,We(a.F,a))};
var pf=function(a){var b=null;a.k&&(b=a.k,a.k=b.next,b.next=null);a.k||(a.n=null);return b};var qf=function(a,b,c,d){b.j&&(b.j.l=null);if(2==c)b.l.call(b.context,d);else if(null!=b.k){if(!b.n)for(;a&&a.A;a=a.l)a.A=!1;b.k.call(b.context,d)}lf.put(b)};var vf=function(a,b){a.A=!0;We(function(){a.A&&wf.call(null,b)})};var tf=function(a){m.wa.call(this,a)};var xf=function(a){this.j=a;a.then((0,m.q)(function(){},this))};
var yf=function(a,b,c,d){for(var e=Array(arguments.length-3),f=3;f<arguments.length;f++)e[f-3]=arguments[f];f=zf(a,b,c).then(function(a){return a.apply(null,e)});return new xf(f)};
var zf=function(a,b,c){var d="https://www.gstatic.com/feedback/js/help/"+(a&&"prod"!=a&&"canary"!=a?"nonprod":"prod")+"/"+b;if(a=Af[c])return a;a=(a=m.p(c))?new m.ff(m.gf,a):(new m.ff(function(a,b){var c=window.document.createElement("script");c.async=!0;c.src=d;c.onload=c.onreadystatechange=function(){c.readyState&&"loaded"!=c.readyState&&"complete"!=c.readyState||a()};c.onerror=b;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(c)})).then(function(){var a=m.p(c);
if(!a)throw Error("Failed to load "+c+" from "+d);return a});return Af[c]=a};var Bf=function(a,b,c){a.j.then(function(a){var e=a[b];if(!e)throw Error("Method not found: "+b);return e.apply(a,c)})};var Cf=function(a){this.j=a};
var Df=function(a,b){var c=b||{},c={apiKey:c.Jf||c.apiKey,environment:c.Uf||c.environment,helpCenterPath:c.NH||c.helpCenterPath,locale:c.locale||c.locale||"en".replace(/-/g,"_"),productData:c.YH||c.productData,receiverUri:c.ZH||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window},c=yf("prod","service/lazy.min.js","help.service.Lazy.create",a,c);return new Cf(c)};var Ef=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};
var Ff=function(a){return(a=a.exec(m.Bc))?a[1]:""};m.Gf=function(a){return 0<=m.Ja(If,a)};var Jf=function(){return m.D?m.Gf("8"):m.Kf?m.Gf("15"):m.Lf?m.Gf("5"):m.Mf};
var Nf=function(){this.j=this.minor=this.major=0;this.k="";var a=m.p("window.navigator.plugins"),b=m.p("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==
a.charAt(0)||"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.k=b;b=a;this.major=b[0];this.minor=b[1];this.j=b[2];if(0>=this.major){var h,k,n,v;if(m.Of)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){h=null}else n=window.document.body,v=window.document.createElement("object"),v.setAttribute("type","application/x-shockwave-flash"),h=n.appendChild(v);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(J){k=""}n&&v&&n.removeChild(v);
(h=k||"")?(h=h.split(" ")[1].split(","),h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.major=h[0];this.minor=h[1];this.j=h[2]}};var Pf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.j>=b[2]};
var Qf=function(a){return-1<a.k.indexOf("Gnash")&&-1==a.k.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.j?!1:9<=a.major};var Rf=function(a){return m.Sf?!Pf(a,11,2):m.Tf?!Pf(a,11,3):!Qf(a)};m.Uf=function(){return m.Jc?"Webkit":m.Ic?"Moz":m.D?"ms":m.Vf?"O":null};m.Wf=function(){return m.Jc?"-webkit":m.Ic?"-moz":m.D?"-ms":m.Vf?"-o":null};m.Xf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.Yf=function(a,b){return a&&b?b instanceof m.Xf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.Zf=function(a,b){var c=$f[b];if(!c){var d=m.Na(b),c=d;void 0===a.style[d]&&(d=m.Uf()+m.Oa(d),void 0!==a.style[d]&&(c=d));$f[b]=c}return c};m.ag=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.bg=function(a,b){a.style.height=m.ag(b,!0)};m.cg=function(a,b){a.style.width=m.ag(b,!0)};
m.dg=function(a,b){a.style.display=b?"":"none"};m.eg=function(a,b){(a=m.E(a))&&a.style&&(m.dg(a,b),m.ne(a,"hid",!b))};m.N=function(a){(0,m.A)(arguments,function(a){m.eg(a,!0)})};
var fg=function(a,b){var c=m.x("FEEDBACK_LOCALE_LANGUAGE"),d=m.gg,e=m.x("FEEDBACK_LOCALE_EXTRAS",{});a?m.Kb(d,a):m.Kb(d,e);try{var f,h=m.p("yt.player.getPlayerByElement");(f=h?h("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var k=Nf.getInstance();d.flashVersion=k.getVersion().join(".");f&&(d.playback_id=f.getVideoData().cpn)}catch(n){}b&&m.Kb(d,{trackingParam:b});return{helpCenterPath:"/youtube",locale:c,productData:d}};
var hg=function(){var a=m.x("SESSION_INDEX"),b=m.x("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.ig=function(a,b){try{var c=(a||"59")+"",d=fg(b),e=hg();Df(c,d).l(e);return!1}catch(f){return!0}};
m.jg=function(a,b,c,d,e,f,h,k){b=(b||"59")+"";d=fg(d,h);a={context:c,anchor:a,enableSendFeedback:f?!1:!0,defaultHelpArticleId:k};m.Kb(a,hg());try{var n=Df(b,d);if(e&&!kg)try{n.k(a),kg=!0}catch(v){}n.n(a);return!1}catch(w){return!0}};m.lg=function(a,b,c,d){return m.jg(void 0,d,b,c,void 0,void 0,void 0,a)};m.mg=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.tf=!1;this.Fr=!0};
m.ng=function(a,b){m.mg.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.hb=this.state=null;a&&this.init(a,b)};m.og=function(a){return!(!a||!a[m.pg])};var qg=function(a,b,c,d,e){this.nf=a;this.j=null;this.src=b;this.type=c;this.Xh=!!d;this.kd=e;this.key=++rg;this.sg=this.Vh=!1};
var sg=function(a){a.sg=!0;a.nf=null;a.j=null;a.src=null;a.kd=null};m.tg=function(a){this.src=a;this.j={};this.k=0};m.ug=function(a,b){var c=b.type;if(!(c in a.j))return!1;var d=m.Ua(a.j[c],b);d&&(sg(b),0==a.j[c].length&&(delete a.j[c],a.k--));return d};m.vg=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.sg&&f.nf==b&&f.Xh==!!c&&f.kd==d)return e}return-1};
m.wg=function(a,b,c,d,e){if(m.ia(b)){for(var f=0;f<b.length;f++)m.wg(a,b[f],c,d,e);return null}c=m.xg(c);return m.og(a)?a.Q(b,c,d,e):m.yg(a,b,c,!1,d,e)};m.yg=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=!!e,k=m.zg(a);k||(a[Ag]=k=new m.tg(a));c=k.add(b,c,d,e,f);if(c.j)return c;d=Bg();c.j=d;d.src=a;d.nf=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(Cg(b.toString()),d);Dg++;return c};
var Bg=function(){var a=Eg,b=Fg?function(c){return a.call(b.src,b.nf,c)}:function(c){c=a.call(b.src,b.nf,c);if(!c)return c};return b};m.Gg=function(a){if(m.ma(a)||!a||a.sg)return!1;var b=a.src;if(m.og(b))return b.ys(a);var c=a.type,d=a.j;b.removeEventListener?b.removeEventListener(c,d,a.Xh):b.detachEvent&&b.detachEvent(Cg(c),d);Dg--;(c=m.zg(b))?(m.ug(c,a),0==c.k&&(c.src=null,b[Ag]=null)):sg(a);return!0};var Cg=function(a){return a in Hg?Hg[a]:Hg[a]="on"+a};
var Ig=function(a,b,c,d){var e=!0;if(a=m.zg(a))if(b=a.j[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Xh==c&&!f.sg&&(f=Jg(f,d),e=e&&!1!==f)}return e};var Jg=function(a,b){var c=a.nf,d=a.kd||a.src;a.Vh&&m.Gg(a);return c.call(d,b)};
var Eg=function(a,b){if(a.sg)return!0;if(!Fg){var c=b||m.p("window.event"),d=new m.ng(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.tf&&0<=k;k--){d.currentTarget=c[k];var n=Ig(c[k],f,!0,d),e=e&&n}for(k=0;!d.tf&&k<c.length;k++)d.currentTarget=c[k],n=Ig(c[k],f,!1,d),e=e&&n}return e}return Jg(a,
new m.ng(b,this))};m.zg=function(a){a=a[Ag];return a instanceof m.tg?a:null};m.xg=function(a){if(m.na(a))return a;a[Kg]||(a[Kg]=function(b){return a.handleEvent(b)});return a[Kg]};m.Lg=function(){var a=m.Ie("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Mg[d]=c.toString())}};var Ng=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
var Og=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Pg=function(a){a=void 0!==m.Mg[a]?m.Mg[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Qg=function(a,b){return!!((m.Pg("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Rg=function(a,b,c){if(b){a=m.ka(a)?m.Qc(a):a;c=m.se(c);var d=m.Jb(c.attrs);d.tabindex=0;var e=m.Jb(c.params);e.flashvars=m.Ad(c.args);if(m.Of){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Sg=function(a,b){a=m.ka(a)?m.Qc(a):a;b=m.se(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Nf.getInstance();Pf(c,b.minVersion)?(c=Tg(b,c),Rg(a,c,b)):Ug(a,b,c)};
var Vg=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.se(a);var d=!!b,e=m.E(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);ge(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Nf.getInstance();if(Pf(h,a.minVersion)){var k=Tg(a,h),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=k||d)&&Rg(f,k,a);Rf(h)&&Wg()}else Ug(f,a,h);c&&c()}else m.y(function(){Vg(a,
b,c)},50)}};var Ug=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.lb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Tg=function(a,b){var c;(c=Qf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Pf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
var Wg=function(){var a=m.E("flash10-promo-div"),b=m.Qg(m.Lg.getInstance(),107);a&&!b&&m.N(a)};m.Xg=function(a,b){var c=a.match(Yg);window.spf.style.load(a,c?c[1]:"",b)};var Zg=function(){if(2.2==$g)return!0;var a;a=m.p("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.l("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};
var ah=function(){};m.bh=function(){};m.ch=function(a){this.j=a};m.dh=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};var eh=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};
m.fh=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.gh=function(a){return(new m.hh(void 0)).Hb(a)};m.hh=function(a){this.j=a};
var ih=function(a,b,c){switch(typeof b){case "string":jh(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],ih(a,a.j?a.j.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&
(c.push(d),jh(f,c),c.push(":"),ih(a,a.j?a.j.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var jh=function(a,b){b.push('"',a.replace(kh,function(a){if(a in lh)return lh[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return lh[a]=e+b.toString(16)}),'"')};m.mh=function(a){this.j=a};var nh=function(a){this.j=a};var oh=function(a){this.data=a};var ph=function(a){return!m.da(a)||a instanceof oh?a:new oh(a)};
m.qh=function(a){this.j=a};m.rh=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.G)()||!!b&&b>(0,m.G)()};m.sh=function(a){this.j=a};m.th=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.G)()+1E3*d:0;if((d=d?m.uh:m.vh)&&window.JSON){m.ka(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.wh=function(a){if(!m.vh&&!m.uh||!window.JSON)return null;var b;try{b=m.vh.get(a)}catch(c){}if(!m.ka(b))try{b=m.uh.get(a)}catch(d){}if(!m.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var xh=function(){var a={volume:100,muted:!1},b=m.wh("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.yc(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var yh=function(a,b){m.u.call(this);this.n=this.B=a;this.R=b;this.F=!1;this.k={};this.Za=this.V=null;this.T=new m.ab;m.Ya(this,this.T);this.A={};this.G=this.gb=this.l=this.Nb=this.j=null;this.W=!1;this.N=this.L=this.xb=this.C=null;this.jb={};this.Kd=["onReady"];this.pb=[];this.Wb=null;this.xc=0;this.Ia={};zh(this);this.Uc("onVolumeChange",(0,m.q)(this.QA,this));this.Uc("onError",(0,m.q)(this.MA,this));this.Uc("onTabOrderChange",(0,m.q)(this.tu,this));this.Uc("onTabAnnounce",(0,m.q)(this.pn,this));
this.Uc("WATCH_LATER_VIDEO_ADDED",(0,m.q)(this.RA,this));this.Uc("WATCH_LATER_VIDEO_REMOVED",(0,m.q)(this.SA,this));this.Uc("onMouseWheelCapture",(0,m.q)(this.BA,this));this.Uc("onMouseWheelRelease",(0,m.q)(this.CA,this));this.Uc("onMouseMoveCapture",(0,m.q)(this.zA,this));this.Uc("onAdAnnounce",(0,m.q)(this.pn,this));this.wb=!1;this.Tc=m.Mf||m.Kf;this.Pa=this.va=null;m.wg(this.B,"mousewheel",this.Jq,!1,this);m.wg(this.B,"wheel",this.Jq,!1,this)};
var Ah=function(a,b){a.Nb=b;a.j=b.clone();a.l=a.j.attrs.id||a.l;"video-player"==a.l&&(a.l=a.R,a.j.attrs.id=a.R);a.n.id==a.l&&(a.l=a.l+"-player",a.j.attrs.id=a.l);a.j.args.enablejsapi="1";a.j.args.playerapiid=a.R;a.gb||(a.gb=Bh(a,a.j.args.jsapicallback||"onYouTubePlayerReady"));a.j.args.jsapicallback=null;var c=a.j.attrs.width;c&&m.cg(a.n,Number(c)||c);(c=a.j.attrs.height)&&m.bg(a.n,Number(c)||c);a.n.style.overflow="hidden"};
var Ch=function(a){a.j.loaded||(a.j.loaded=!0,"0"!=a.j.args.autoplay?a.k.loadVideoByPlayerVars(a.j.args):a.k.cueVideoByPlayerVars(a.j.args))};var Dh=function(a){if(!m.da(a.j.disable.flash)){var b=a.j.disable,c;c=Pf(Nf.getInstance(),a.j.minVersion);b.flash=!c}return!a.j.disable.flash};
var Eh=function(a){var b=Fh(a);b&&b.stopVideo&&b.stopVideo();if(Dh(a)){var c=a.j;b&&b.getUpdatedConfigurationData&&(c=m.se(b.getUpdatedConfigurationData()));c.args.autoplay=1;c.args.html5_unavailable="1";Ah(a,c);Gh(a,"flash")}};
var Gh=function(a,b){if(!a.Ua()){if(!b){var c;if(!(c=!a.j.html5&&Dh(a))){if(!m.da(a.j.disable.html5)){if(c=Zg())c=Hh(a)||a.j.assets.js;a.j.disable.html5=!c;c||(a.j.args.html5_unavailable="1")}c=!!a.j.disable.html5}b=c?Dh(a)?"flash":"unsupported":"html5"}("flash"==b?a.FD:"html5"==b?a.GD:a.ID).call(a)}};var Hh=function(a){var b=!0,c=Fh(a);c&&a.j&&(a=a.j,b=m.C(c,"version")==a.assets.js);return b&&!!m.p("yt.player.Application.create")};
var Fh=function(a){var b=m.E(a.l);!b&&a.n&&a.n.querySelector&&(b=a.n.querySelector("#"+a.l));return b};var Ih=function(a,b,c){var d=b[c];return function(){try{return a.Wb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Wb=e,m.ib(e,"WARNING"))}}};
var zh=function(a){a.F=!1;if(a.Za)for(var b in a.A)a.Za(b,a.A[b]);for(var c in a.Ia)m.gb((0,window.parseInt)(c,10));a.Ia={};a.V=null;a.Za=null;for(var d in a.k)a.k[d]=null;a.k.addEventListener=(0,m.q)(a.Uc,a);a.k.removeEventListener=(0,m.q)(a.zC,a);a.k.destroy=(0,m.q)(a.dispose,a);a.k.getLastError=(0,m.q)(a.Zu,a);a.k.getPlayerType=(0,m.q)(a.av,a);a.k.getCurrentVideoConfig=(0,m.q)(a.Xu,a);a.k.loadNewVideoConfig=(0,m.q)(a.Qm,a);a.k.isReady=(0,m.q)(a.VD,a)};
var Bh=function(a,b){var c=b;if("string"==typeof b){if(a.jb[b])return a.jb[b];c=function(){var a=m.p(b);a&&a.apply(m.ea,arguments)};a.jb[b]=c}return c?c:null};var Jh=function(a,b){var c="ytPlayer"+b+a.R;a.A[b]=c;m.ea[c]=function(c){var e=m.y(function(){a.Ua()||(a.T.X(b,c),m.Hb(a.Ia,String(e)))},0);m.Ib(a.Ia,String(e),!0)};return c};var Kh=function(a){return(a=Fh(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Lh=function(a){m.Md("dcp");a.cancel();zh(a);a.G=null;a.j&&(a.j.loaded=!1);var b=Fh(a);"html5"==Kh(a)?a.xb=b:b&&b.destroy&&b.destroy();m.bd(a.B);m.M(a.pb);a.pb.length=0;a.L=null;a.N=null};m.Mh=function(a,b){a=m.ka(a)?m.Qc(a):a;b=m.se(b);var c=Nh+"_"+m.pa(a),d=Oh[c];if(d)return d.Qm(b),d.k;d=new yh(a,c);Oh[c]=d;m.B("player-added",d.k);m.Za(d,m.r(Ph,d));m.y(function(){d.Qm(b)},0);return d.k};var Qh=function(){for(var a in Oh){var b=Oh[a];b&&b.cancel()}};
m.Rh=function(a){if(a=m.E(a))a=Nh+"_"+m.pa(a),(a=Oh[a])&&a.dispose()};var Ph=function(a){Oh[a.getId()]=null};m.Sh=function(a){a=m.E(a);if(!a)return null;var b=Nh+"_"+m.pa(a),c=Oh[b];c||(c=new yh(a,b),Oh[b]=c);return c.k};m.Th=function(){return m.H(m.E("page-container"),"remote-connected")};
var Uh=function(){m.l("yt.abuse.botguardInitialized",te,void 0);m.l("yt.abuse.invokeBotguard",m.ve,void 0);m.l("yt.player.exports.navigate",m.Qe,void 0);m.l("yt.player.embed",m.Mh,void 0);m.l("yt.player.destroy",m.Rh,void 0);m.l("yt.player.cancelAll",Qh,void 0);m.l("yt.player.getPlayerByElement",m.Sh,void 0);m.l("yt.player.exports.feedbackStart",m.ig,void 0);m.l("yt.player.exports.feedbackShowArticle",m.lg,void 0);m.l("yt.util.activity.init",m.Je,void 0);m.l("yt.util.activity.getTimeSinceActive",
m.Le,void 0);m.l("yt.util.activity.setTimestamp",Ke,void 0);var a=m.p("ytplayer.config");Vh(a);m.p("ytspf.enabled")&&(Wh=m.fb(Xh,5E3),(a=m.Yh())?(a.addEventListener("onReady",Xh),a.addEventListener("onStateChange",Xh)):Zh("unable to init PP monitor"))};
var Vh=function(a){Qh();if(a=a||null){var b=m.Yh(),c=!0,d=m.$h;m.$h=null;b&&b.getVideoData&&d&&(c=b.getVideoData(),c=!!d.fullscreen||c.video_id!=a.args.video_id||c.list!=a.args.list||c.video_id!=d.videoId||c.list!=d.listId);c?(ai="",m.Mh("player-api",a)):b.playVideo();a=m.se(a);a.loaded=!0}Xh();m.l("ytplayer.config",a,void 0)};m.Yh=function(){var a=m.p("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Xh=function(){var a=m.Yh();if(a){var b;b=m.E("player");b=!b||m.H(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==m.x("PAGE_NAME"),e=m.Th();!c||d||e||(Zh("PP playing off watch (paused)"),a.pauseVideo());b&&d?Zh("PP off-screen on watch"):b||d||Zh("PP !off-screen off watch")}};var Zh=function(a){var b=m.x("PAGE_NAME");b&&(b=[b,ai,m.p("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.l("yt.www.persistentplayer.issue",a,void 0),m.ib(Error(a),"WARNING"))};
var bi=function(){m.Md("ol");ci("init");var a=m.x("PAGE_NAME");a&&ci("init-"+a);ee()};var ci=function(a){m.ub()?di.push(m.vb(m.r(m.tb,a),0)):m.B(a)};var ei=function(){m.yb(di);di.length=0;var a=m.x("PAGE_NAME");a&&m.tb("dispose-"+a);m.tb("dispose")};var fi=function(){bi()};var gi=function(){m.x("TIMING_REPORT_ON_UNLOAD")&&Pd(!0);fe("u");ce("u");ei()};
var hi=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),h=!1,k=0,n=f.length;k<n;k++)if(0<f[k].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.ib(e))};var ii=function(){ji=1;ki=0;m.x("TIMING_REPORT_ON_UNLOAD")&&Pd(!0);fe("n");ce("n");Sd();m.x("CSI_TRACK_ON_BEGIN")&&Qd("nb");Od("mark_navigation_requested");li(mi);m.tb("navigate")};
var ni=function(a){a=a.detail.part||a.detail.partial;m.Md("nc"+ki);++ki;var b=1==ji;ji=2;b?(li(oi),pi()):li(qi);(a=a.data&&a.data.swfcfg)&&ri(a)};var si=function(){};var ti=function(a){a=a.detail.response;var b=1==ji;ji=3;b&&(li(ui),pi());(a=a.data&&a.data.swfcfg)&&ri(a)};
var vi=function(a){m.Md("nd");a=a.detail.response;m.wi=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Rd(void 0).yt_nav=b;Qd("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Rd(void 0).srt=b;b=a.spfCached?"hot":"warm";Rd(void 0).yt_lt=b;b=+!!a.spfPrefetched;Rd(void 0).yt_pft=b;b=a.responseStart-a.fetchStart;Xd(void 0).span.req=b;"redirectStart"in a&&Wd(a);li(xi);window.document.getElementById("content").style.height="";bi();ji=0};
var yi=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.ib(a)};var zi=function(a){a=m.Ad({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.ke(a)};var Ai=function(){Bi()};var Ci=function(){};
var pi=function(){m.x("USE_SPF_SCROLL_POSITION")||window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");ei();for(var b in m.db)delete m.db[b];m.l("ytplayer.config",null,void 0);if((a=m.Yh())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())ai=a,(a=m.E("movie_player"))&&a.stopVideo?(a.stopVideo(),ai="recovered"):ai="missing2"}else ai="missing";Xh()};var ri=function(a){"cfg"in Nd(void 0)||m.Md("cfg");Vh(a)};
var li=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));m.xb(Di);Di=m.wb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";m.gb(Ei);Ei=m.y(function(){b.className=e},c)},0)};
var Bi=function(){var a=xi[0]+50;m.gb(Ei);Ei=m.y(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var Fi=function(){m.zb.call(this,"www/base");this.l=0};var Gi=function(a){(a=a.detail.name)&&Db(a)};m.ba=[];m.Hi=m.Hi||{};m.ea=this;qa="closure_uid_"+(1E9*Math.random()>>>0);ra=0;m.G=Date.now||function(){return+new Date};
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};ua[" "]=m.fa;m.t(m.wa,Error);m.wa.prototype.name="CustomError";var Ba,Ca,Da,Ea,Fa,Ga,Aa;m.Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};Ba=/&/g;Ca=/</g;Da=/>/g;Ea=/"/g;Fa=/'/g;Ga=/\x00/g;Aa=/[\x00&<>"']/;m.Ii=2147483648*Math.random()|0;m.Wa=Array.prototype;m.Ta=m.Wa.indexOf?function(a,b,c){return m.Wa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ka(a))return m.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.Ji=m.Wa.lastIndexOf?function(a,b,c){return m.Wa.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ka(a))return m.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.A=m.Wa.forEach?function(a,b,c){m.Wa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.me=m.Wa.filter?function(a,b,c){return m.Wa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=m.ka(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var n=h[k];b.call(c,n,k,a)&&(e[f++]=n)}return e};m.Ki=m.Wa.map?function(a,b,c){return m.Wa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=m.ka(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.Li=m.Wa.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.Wa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.A)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Mi=m.Wa.some?function(a,b,c){return m.Wa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.Ni=m.Wa.every?function(a,b,c){return m.Wa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.u.prototype.Vb=!1;m.u.prototype.Ua=function(){return this.Vb};m.u.prototype.dispose=function(){this.Vb||(this.Vb=!0,this.M())};m.u.prototype.M=function(){if(this.rb)for(;this.rb.length;)this.rb.shift()()};m.t(m.ab,m.u);m.g=m.ab.prototype;m.g.subscribe=function(a,b,c){var d=this.Sc[a];d||(d=this.Sc[a]=[]);var e=this.n;this.j[e]=a;this.j[e+1]=b;this.j[e+2]=c;this.n=e+3;d.push(e);return e};m.g.Cf=function(a,b,c){if(a=this.Sc[a]){var d=this.j;if(a=m.Pa(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Hc(a)}return!1};m.g.Hc=function(a){if(0!=this.l)return this.k.push(a),!1;var b=this.j[a];if(b){var c=this.Sc[b];c&&m.Ua(c,a);delete this.j[a];delete this.j[a+1];delete this.j[a+2]}return!!b};
m.g.X=function(a,b){var c=this.Sc[a];if(c){this.l++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var h=c[e];this.j[h+1].apply(this.j[h+2],d)}this.l--;if(0<this.k.length&&0==this.l)for(;c=this.k.pop();)this.Hc(c);return 0!=e}return!1};m.g.clear=function(a){if(a){var b=this.Sc[a];b&&((0,m.A)(b,this.Hc,this),delete this.Sc[a])}else this.j.length=0,this.Sc={}};m.g.ib=m.aa(3);
m.g.M=function(){m.ab.D.M.call(this);this.clear();this.k.length=0};m.db=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};m.l("yt.config_",m.db,void 0);m.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.kb=window.yt&&window.yt.msgs_||{};m.l("yt.msgs_",m.kb,void 0);m.Of="Microsoft Internet Explorer"==window.navigator.appName;var Oi=m.p("yt.pubsub.instance_")||new m.ab;m.ab.prototype.subscribe=m.ab.prototype.subscribe;m.ab.prototype.unsubscribeByKey=m.ab.prototype.Hc;m.ab.prototype.publish=m.ab.prototype.X;m.ab.prototype.clear=m.ab.prototype.clear;m.l("yt.pubsub.instance_",Oi,void 0);var pb=m.p("yt.pubsub.subscribedKeys_")||{};m.l("yt.pubsub.subscribedKeys_",pb,void 0);var rb=m.p("yt.pubsub.topicToKeys_")||{};m.l("yt.pubsub.topicToKeys_",rb,void 0);var qb=m.p("yt.pubsub.isSynchronous_")||{};
m.l("yt.pubsub.isSynchronous_",qb,void 0);var nb=m.p("yt.pubsub.skipSubId_")||null;m.l("yt.pubsub.skipSubId_",nb,void 0);m.g=m.zb.prototype;m.g.HC=function(){this.Xi()||this.init()};m.g.enable=function(){this.j=1;(0,m.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.HC,this),this.subscribe("dispose-"+a,this.dispose,this),m.x("PAGE_NAME")==a&&m.Ab(this))},this)};m.g.init=function(){m.xb(this.k);this.j=2;this.B&&this.B()};m.g.Xi=function(){return 2==this.j};m.g.dispose=function(){this.j=3;m.xb(this.k);this.A&&this.A()};m.g.disable=function(){this.j=4;this.clear();try{this.dispose()}catch(a){m.ib(a)}};
m.g.subscribe=function(a,b,c){a=m.z(a,b,c);this.n.push(a);return a};m.g.clear=function(){m.sb(this.n);this.n=[]};var Cb=m.p("yt.modules.registry_")||{};m.l("yt.modules.registry_",Cb,void 0);var Lb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var pc=Mb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Pi=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Qi=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.Nb.prototype.jf=!0;m.Nb.prototype.ve=function(){return this.j};m.Nb.prototype.toString=function(){return"Const{"+this.j+"}"};var Ob={};m.Qb.prototype.jf=!0;var Rb={};m.Qb.prototype.ve=function(){return this.j};var nc=m.Tb(""),mc=/^[-,."'%_!# a-zA-Z0-9]+$/;m.Ub.prototype.jf=!0;m.Ub.prototype.ve=function(){return this.j};m.Ub.prototype.cl=!0;m.Ub.prototype.Vg=function(){return 1};var Yb=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,$b=/[()']|%5B|%5D|%25/g,ac={"'":"%27","(":"%28",")":"%29","%5B":"[","%5D":"]","%25":"%"},Vb={};bc.prototype.jf=!0;bc.prototype.ve=function(){return""};bc.prototype.cl=!0;bc.prototype.Vg=function(){return 1};var cc={};var hc,oc,ic,ec;m.dc.prototype.cl=!0;m.dc.prototype.Vg=function(){return this.k};m.dc.prototype.jf=!0;m.dc.prototype.ve=function(){return this.j};hc=/^[a-zA-Z0-9-]+$/;oc={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};ic={EMBED:!0,IFRAME:!0,LINK:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,TEMPLATE:!0};ec={};m.Ri=m.lc("<!DOCTYPE html>",0);m.Si=m.lc("",0);var tc={};var wc=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,xc=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.g=m.zc.prototype;m.g.clone=function(){return new m.zc(this.x,this.y)};m.g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};m.g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};m.g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.x*=a;this.y*=c;return this};a:{var Ti=m.ea.navigator;if(Ti){var Ui=Ti.userAgent;if(Ui){m.Bc=Ui;break a}}m.Bc=""};var Wi,Nc,Mc,$i,aj;m.Vf=Cc();m.D=Dc();m.Ic=m.Ac("Gecko")&&!(m.Ha(m.Bc.toLowerCase(),"webkit")&&!Fc())&&!(m.Ac("Trident")||m.Ac("MSIE"))&&!Fc();m.Jc=m.Ha(m.Bc.toLowerCase(),"webkit")&&!Fc();m.Jc&&m.Ac("Mobile");m.Tf=m.Ac("Macintosh");m.Sf=m.Ac("Windows");m.Vi=m.Ac("Linux")||m.Ac("CrOS");Wi=m.ea.navigator||null;Wi&&m.Ha(Wi.appVersion||"","X11");m.Xi=m.Ac("Android");m.Yi=m.Gc();m.Zi=m.Ac("iPad");
Nc=function(){if(m.Vf&&m.ea.opera){var a=m.ea.opera.version;return m.na(a)?a():a}var a="",b=Hc();b&&(a=b?b[1]:"");return m.D&&!Fc()&&(b=Kc(),b>(0,window.parseFloat)(a))?String(b):a}();Mc={};$i=m.ea.document;aj=Kc();m.Pc=!$i||!m.D||!aj&&Fc()?void 0:aj||("CSS1Compat"==$i.compatMode?(0,window.parseInt)(Nc,10):5);var Zc;Zc=!m.D||m.Oc(9);m.bj=!m.Ic&&!m.D||m.D&&m.Oc(9)||m.Ic&&m.Lc("1.9.1");m.cj=m.D&&!m.Lc("9");m.dj=m.D||m.Vf||m.Jc;m.ej=m.D&&!m.Oc(9);var Tc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.fj=m.jd(!1);m.gj=m.jd(!0);m.hj=m.jd(null);m.nd="StopIteration"in m.ea?m.ea.StopIteration:Error("StopIteration");m.ld.prototype.next=function(){throw m.nd;};m.ld.prototype.Ob=function(){return this};var ud=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,sd=m.Jc;var Gd={},Fd=0,ij=m.p("yt.net.ping.workerUrl_")||null;m.l("yt.net.ping.workerUrl_",ij,void 0);m.Hd.prototype.Hb=function(){return{version:this.version,args:this.args}};m.Id.prototype.toString=function(){return this.j};var jj=m.p("yt.pubsub2.instance_")||new m.ab;m.ab.prototype.subscribe=m.ab.prototype.subscribe;m.ab.prototype.unsubscribeByKey=m.ab.prototype.Hc;m.ab.prototype.publish=m.ab.prototype.X;m.ab.prototype.clear=m.ab.prototype.clear;m.l("yt.pubsub2.instance_",jj,void 0);m.kj=m.p("yt.pubsub2.subscribedKeys_")||{};m.l("yt.pubsub2.subscribedKeys_",m.kj,void 0);m.lj=m.p("yt.pubsub2.topicToKeys_")||{};m.l("yt.pubsub2.topicToKeys_",m.lj,void 0);m.mj=m.p("yt.pubsub2.isAsync_")||{};
m.l("yt.pubsub2.isAsync_",m.mj,void 0);m.l("yt.pubsub2.skipSubKey_",null,void 0);m.t(Ld,m.Hd);var de=new m.Id("timing-sent",Ld);var Zd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Ud=(0,m.q)(Zd.clearResourceTimings||Zd.webkitClearResourceTimings||Zd.mozClearResourceTimings||Zd.msClearResourceTimings||Zd.oClearResourceTimings||m.fa,Zd),Od=Zd.mark?function(a){Zd.mark(a)}:m.fa;m.je=m.td;var pe={enablejsapi:1},qe={},re={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};oe.prototype.clone=function(){var a=new oe,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.Jb(c):a[b]=c}return a};m.ue=null;m.nj=m.Jc?"webkit":m.Ic?"moz":m.D?"ms":m.Vf?"o":"";m.oj=m.p("yt.dom.getNextId_");if(!m.oj){m.oj=function(){return++pj};m.l("yt.dom.getNextId_",m.oj,void 0);var pj=0};m.g=m.xe.prototype;m.g.hb=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.touches=null;m.g.changedTouches=null;m.g.preventDefault=function(){this.hb.returnValue=!1;this.hb.preventDefault&&this.hb.preventDefault()};
m.g.stopPropagation=function(){this.hb.cancelBubble=!0;this.hb.stopPropagation&&this.hb.stopPropagation()};m.g.stopImmediatePropagation=function(){this.hb.cancelBubble=!0;this.hb.stopImmediatePropagation&&this.hb.stopImmediatePropagation()};var ye={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.Ae=m.p("yt.events.listeners_")||{};m.l("yt.events.listeners_",m.Ae,void 0);var Be=m.p("yt.events.counter_")||{count:0};m.l("yt.events.counter_",Be,void 0);m.Fe=/\s*;\s*/;m.g=m.De.prototype;m.g.isEnabled=function(){return window.navigator.cookieEnabled};m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.G)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.Fe),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=m.da(this.get(a));this.set(a,"",0,b,c);return d};m.g.Bb=m.aa(4);m.g.kb=m.aa(5);m.g.isEmpty=function(){return!this.j.cookie};m.g.ib=m.aa(2);m.g.Rf=m.aa(6);m.g.clear=function(){for(var a=m.Ee(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.He=new m.De(window.document);m.He.k=3950;Re.prototype.get=function(){var a;0<this.k?(this.k--,a=this.j,this.j=a.next,a.next=null):a=this.l();return a};Re.prototype.put=function(a){this.n(a);this.k<this.A&&(this.k++,a.next=this.j,this.j=a)};var bf;var cf=new Re(function(){return new Ve},function(a){a.reset()},100);Ue.prototype.add=function(a,b){var c=cf.get();c.set(a,b);this.k?this.k.next=c:this.j=c;this.k=c};Ue.prototype.remove=function(){var a=null;this.j&&(a=this.j,this.j=this.j.next,this.j||(this.k=null),a.next=null);return a};Ve.prototype.set=function(a,b){this.Yd=a;this.scope=b;this.next=null};Ve.prototype.reset=function(){this.next=this.scope=this.Yd=null};var Xe,Ze=!1,$e=new Ue;jf.prototype.reset=function(){this.context=this.k=this.l=this.j=null;this.n=!1};var lf=new Re(function(){return new jf},function(a){a.reset()},100);m.ff.prototype.then=function(a,b,c){return m.sf(this,m.na(a)?a:null,m.na(b)?b:null,c)};m.df(m.ff);m.ff.prototype.cancel=function(a){0==this.j&&We(function(){var b=new tf(a);of(this,b)},this)};m.ff.prototype.G=function(a){this.j=0;hf(this,2,a)};m.ff.prototype.L=function(a){this.j=0;hf(this,3,a)};
m.ff.prototype.F=function(){for(var a=null;a=pf(this);)qf(this,a,this.j,this.C);this.B=!1};var wf=Se;m.t(tf,m.wa);tf.prototype.name="cancel";var Af={};Cf.prototype.l=function(a){Bf(this.j,"startFeedback",arguments)};Cf.prototype.n=function(a){Bf(this.j,"startHelp",arguments)};Cf.prototype.k=function(a){Bf(this.j,"loadChatSupport",arguments)};var qj=!1,rj="";
if(window.navigator.plugins&&window.navigator.plugins.length){var sj=window.navigator.plugins["Shockwave Flash"];sj&&(qj=!0,sj.description&&(rj=Ef(sj.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(qj=!0,rj="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var tj=window.navigator.mimeTypes["application/x-shockwave-flash"];(qj=tj&&tj.enabledPlugin)&&(rj=Ef(tj.enabledPlugin.description))}else try{var uj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),qj=
!0,rj=Ef(uj.GetVariable("$version"))}catch(aaa){try{uj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),qj=!0,rj="6.0.21"}catch(baa){try{uj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),qj=!0,rj=Ef(uj.GetVariable("$version"))}catch(caa){}}}m.vj=qj;m.wj=rj;var zj;m.Kf=m.Ac("Firefox");m.xj=m.Gc()||m.Ac("iPod");m.yj=m.Ac("iPad");zj=m.Ac("Android")&&!(Ec()||m.Ac("Firefox")||Cc()||m.Ac("Silk"));m.Mf=Ec();m.Lf=m.Ac("Safari")&&!(Ec()||m.Ac("Coast")||Cc()||Dc()||m.Ac("Silk")||m.Ac("Android"))&&!(m.Gc()||m.Ac("iPad")||m.Ac("iPod"));var If=function(){if(m.Kf)return Ff(/Firefox\/([0-9.]+)/);if(m.D||m.Vf)return Nc;if(m.Mf)return Ff(/Chrome\/([0-9.]+)/);if(m.Lf&&!(m.Gc()||m.Ac("iPad")||m.Ac("iPod")))return Ff(/Version\/([0-9.]+)/);if(m.xj||m.yj){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.Bc))return a[1]+"."+a[2]}else if(zj)return(a=Ff(/Android\s+([0-9.]+)/))?a:Ff(/Version\/([0-9.]+)/);return""}();m.l("userfeedback.api.isBrowserSupportedForGenie",function(){return Jf()},void 0);m.l("userfeedback.api.isBrowserSupportedForHelp",Jf,void 0);m.ga(Nf);Nf.prototype.getVersion=function(){return[this.major,this.minor,this.j]};m.g=m.Xf.prototype;m.g.getHeight=function(){return this.bottom-this.top};m.g.clone=function(){return new m.Xf(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return m.Yf(this,a)};m.g.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var $f;$f={};m.Aj=m.Ic?"MozUserSelect":m.Jc?"WebkitUserSelect":null;m.Bj=m.kd(function(){if(m.D)return m.Lc("10.0");var a=window.document.createElement("DIV"),b=m.Wf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");m.qc(a,m.gc("div",{style:c}));a=a.firstChild;b=a.style[m.Na("transition")];return""!=("undefined"!==typeof b?b:a.style[m.Zf(a,"transition")]||"")});var kg;m.gg={};kg=!1;var Fg,Dj;m.Cj=!m.D||m.Oc(9);Fg=!m.D||m.Oc(9);Dj=m.D&&!m.Lc("9");!m.Jc||m.Lc("528");m.Ic&&m.Lc("1.9b")||m.D&&m.Lc("8")||m.Vf&&m.Lc("9.5")||m.Jc&&m.Lc("528");m.Ic&&!m.Lc("8")||m.D&&m.Lc("9");m.mg.prototype.stopPropagation=function(){this.tf=!0};m.mg.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Fr=!1};m.Ej=m.D?"focusin":"DOMFocusIn";m.Fj=m.D?"focusout":"DOMFocusOut";m.Gj=m.Jc?"webkitTransitionEnd":m.Vf?"otransitionend":"transitionend";m.t(m.ng,m.mg);
m.ng.prototype.init=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?m.Ic&&(m.va(d,"nodeName")||(d=null)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=m.Jc||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=m.Jc||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.hb=a;a.defaultPrevented&&this.preventDefault()};m.ng.prototype.stopPropagation=function(){m.ng.D.stopPropagation.call(this);this.hb.stopPropagation?this.hb.stopPropagation():this.hb.cancelBubble=!0};
m.ng.prototype.preventDefault=function(){m.ng.D.preventDefault.call(this);var a=this.hb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Dj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};m.ng.prototype.Hk=m.aa(7);var rg;m.pg="closure_listenable_"+(1E6*Math.random()|0);rg=0;m.tg.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.j[f];a||(a=this.j[f]=[],this.k++);var h=m.vg(a,b,d,e);-1<h?(b=a[h],c||(b.Vh=!1)):(b=new qg(b,this.src,f,!!d,e),b.Vh=c,a.push(b));return b};m.tg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.j))return!1;var e=this.j[a];b=m.vg(e,b,c,d);return-1<b?(sg(e[b]),m.Va(e,b),0==e.length&&(delete this.j[a],this.k--),!0):!1};
m.tg.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.j)if(!a||c==a){for(var d=this.j[c],e=0;e<d.length;e++)++b,sg(d[e]);delete this.j[c];this.k--}return b};var Ag="closure_lm_"+(1E6*Math.random()|0),Hg={},Dg=0,Kg="__closure_events_fn_"+(1E9*Math.random()>>>0);m.ga(m.Lg);m.Mg=m.p("yt.prefs.UserPrefs.prefs_")||{};m.l("yt.prefs.UserPrefs.prefs_",m.Mg,void 0);m.g=m.Lg.prototype;m.g.get=function(a,b){Og(a);Ng(a);var c=void 0!==m.Mg[a]?m.Mg[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){Og(a);Ng(a);if(null==b)throw"ExpectedNotNull";m.Mg[a]=b.toString()};m.g.remove=function(a){Og(a);Ng(a);delete m.Mg[a]};m.g.save=function(){var a;a=[];for(var b in m.Mg)a.push(b+"="+(0,window.escape)(m.Mg[b]));a=a.join("&");m.Ge("PREF",a,63072E3)};
m.g.clear=function(){m.Mg={}};var Yg=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var $g;var Hj=m.Bc,Hj=Hj.toLowerCase();if(m.Ha(Hj,"android")){var Ij=Hj.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Ij)$g=Number(Ij[1]);else{var Jj={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Kj=Hj.match("("+m.Fb(Jj).join("|")+")");$g=Kj?Jj[Kj[0]]:0}}else $g=void 0;m.t(m.bh,ah);m.bh.prototype.ib=m.aa(1);m.bh.prototype.clear=function(){var a=m.pd(this.Ob(!0)),b=this;(0,m.A)(a,function(a){b.remove(a)})};m.t(m.ch,m.bh);m.g=m.ch.prototype;m.g.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.j.getItem(a);if(!m.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.j.removeItem(a)};
m.g.ib=m.aa(0);m.g.Ob=function(a){var b=0,c=this.j,d=new m.ld;d.next=function(){if(b>=c.length)throw m.nd;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.j.clear()};m.g.key=function(a){return this.j.key(a)};m.t(m.dh,m.ch);m.t(eh,m.ch);m.hh.prototype.Hb=function(a){var b=[];ih(this,a,b);return b.join("")};var lh={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},kh=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.mh.prototype.set=function(a,b){m.da(b)?this.j.set(a,m.gh(b)):this.j.remove(a)};m.mh.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.fh(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.mh.prototype.remove=function(a){this.j.remove(a)};m.t(nh,m.mh);nh.prototype.set=function(a,b){nh.D.set.call(this,a,ph(b))};nh.prototype.k=function(a){a=nh.D.get.call(this,a);if(!m.da(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};nh.prototype.get=function(a){if(a=this.k(a)){if(a=a.data,!m.da(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.t(m.qh,nh);m.qh.prototype.set=function(a,b,c){if(b=ph(b)){if(c){if(c<(0,m.G)()){m.qh.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.G)()}m.qh.D.set.call(this,a,b)};m.qh.prototype.k=function(a,b){var c=m.qh.D.k.call(this,a);if(c)if(!b&&m.rh(c))m.qh.prototype.remove.call(this,a);else return c};m.t(m.sh,m.qh);var Lj,Mj;Lj=new m.dh;m.uh=Lj.isAvailable()?new m.sh(Lj):null;Mj=new eh;m.vh=Mj.isAvailable()?new m.sh(Mj):null;m.t(yh,m.u);m.g=yh.prototype;m.g.getId=function(){return this.R};m.g.Qm=function(a,b){this.Ua()||(Ah(this,a),Gh(this,b),this.F&&Ch(this))};m.g.Xu=function(){return this.Nb};
m.g.GD=function(){if(!this.W){var a=Hh(this);if(a&&"html5"==Kh(this))this.G="html5",this.F||this.rg();else if(Lh(this),this.G="html5",a&&this.xb)this.B.appendChild(this.xb),this.rg();else{this.j.loaded=!0;var b=(0,m.q)(function(){var a=this.B,b=this.j.clone();m.p("yt.player.Application.create")(a,b);this.rg()},this);this.C=b;this.W=!0;a?this.C():(this.j.assets.js2?(this.C=a=(0,m.q)(function(){m.uc(this.j.assets.js2,b);this.C=b},this),m.uc(this.j.assets.js,a)):m.uc(this.j.assets.js,this.C),m.Xg(this.j.assets.css))}}};
m.g.FD=function(){var a=this.j.clone();if(!this.L){var b=Fh(this);b&&(this.L=window.document.createElement("span"),this.L.tabIndex=0,this.pb.push(m.L(this.L,"focus",(0,m.q)(this.Bq,this))),this.N=window.document.createElement("span"),this.N.tabIndex=0,this.pb.push(m.L(this.N,"focus",(0,m.q)(this.Bq,this))),m.cd(this.L,b),m.dd(this.N,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Kh(this)?(this.G="flash",this.F||Vg(a,!1,(0,m.q)(this.rg,this))):(Lh(this),this.G=
"flash",this.j.loaded=!0,m.Sg(this.B,a),this.rg())};m.g.Bq=function(){Fh(this).focus()};
m.g.rg=function(){if(!this.Ua()){var a=Fh(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.W=!1,a.isNotServable&&a.isNotServable(this.j.args.video_id))Eh(this);else{zh(this);this.F=!0;a=Fh(this);a.addEventListener&&(this.V=Ih(this,a,"addEventListener"));a.removeEventListener&&(this.Za=Ih(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.k[e]||(this.k[e]=Ih(this,a,e))}for(var f in this.A)this.V(f,
this.A[f]);Ch(this);this.gb&&this.gb(this.k);this.T.X("onReady",this.k);a.apiProxyReady&&a.apiProxyReady()}else this.xc=m.y((0,m.q)(this.rg,this),50)}};m.g.VD=function(){return this.F};m.g.Uc=function(a,b){if(!this.Ua()){var c=Bh(this,b);if(c){if(!m.Sa(this.Kd,a)&&!this.A[a]){var d=Jh(this,a);this.V&&this.V(a,d)}this.T.subscribe(a,c);"onReady"==a&&this.F&&m.y(m.r(c,this.k),0)}}};m.g.zC=function(a,b){if(!this.Ua()){var c=Bh(this,b);c&&this.T.Cf(a,c)}};
m.g.tu=function(a){a=a?fd:ed;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.L||b==this.N||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.pn=function(a){m.B("a11y-announce",a)};m.g.QA=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?xh().volume:m.yc(a.volume,0,100);b.muted=void 0==a.muted?xh().muted:a.muted;m.th("yt-player-volume",b,2592E3)};m.g.MA=function(a){5==a&&Eh(this)};m.g.RA=function(a){m.B("WATCH_LATER_VIDEO_ADDED",a)};
m.g.SA=function(a){m.B("WATCH_LATER_VIDEO_REMOVED",a)};m.g.AA=function(a){if(!m.gd(this.B,m.Ce(a)))this.k.onExternalMouseMove()};m.g.zA=function(){m.wg(window.document,"mousemove",this.AA,!1,this)};m.g.BA=function(){this.Tc&&(this.wb||(this.Pa=m.Uc(window.document)),this.va||(this.va=m.wg(window,"scroll",this.cC,!1,this)));this.wb=!0};m.g.CA=function(){this.va&&(m.Gg(this.va),this.va=null);this.wb=!1};m.g.Jq=function(a){this.wb&&!this.Tc&&a.preventDefault()};
m.g.cC=function(){this.Pa&&window.scrollTo(this.Pa.x,this.Pa.y)};
m.g.ID=function(){Lh(this);this.G="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');b=
this.j.messages.player_fallback||a;a=m.E("player-unavailable");m.E("unavailable-submessage")&&a&&(m.E("unavailable-submessage").innerHTML=b,(b=m.F("icon",a))&&m.sc(b,"icon")&&(b.src=m.C(b,"icon")),m.K(a,"hid"),m.I(m.E("player"),"off-screen-trigger"))};m.g.av=function(){return this.G||Kh(this)};m.g.Zu=function(){return this.Wb};m.g.cancel=function(){if(this.C){var a=this.C,b=m.vc(this.j.assets.js);window.spf.script.ignore(b,a)}m.gb(this.xc);this.W=!1};
m.g.M=function(){Lh(this);this.jb=null;for(var a in this.A)m.ea[this.A[a]]=null;this.k=null;delete this.B;delete this.n;this.j&&(this.Nb=this.j=this.j.fallback=null);yh.D.M.call(this)};var Oh={},Nh="player_uid_"+(1E9*Math.random()>>>0);var Nj=m.p("yt.abuse.botguardInitialized")||te;m.l("yt.abuse.botguardInitialized",Nj,void 0);var Oj=m.p("yt.abuse.invokeBotguard")||m.ve;m.l("yt.abuse.invokeBotguard",Oj,void 0);var Pj=m.p("yt.player.exports.navigate")||m.Qe;m.l("yt.player.exports.navigate",Pj,void 0);var Qj=m.p("yt.player.embed")||m.Mh;m.l("yt.player.embed",Qj,void 0);var Rj=m.p("yt.player.destroy")||m.Rh;m.l("yt.player.destroy",Rj,void 0);var Sj=m.p("yt.player.cancelAll")||Qh;m.l("yt.player.cancelAll",Sj,void 0);
var Tj=m.p("yt.player.getPlayerByElement")||m.Sh;m.l("yt.player.getPlayerByElement",Tj,void 0);var Uj=m.p("yt.player.exports.feedbackStart")||m.ig;m.l("yt.player.exports.feedbackStart",Uj,void 0);var Vj=m.p("yt.player.exports.feedbackShowArticle")||m.lg;m.l("yt.player.exports.feedbackShowArticle",Vj,void 0);var Wj=m.p("yt.util.activity.init")||m.Je;m.l("yt.util.activity.init",Wj,void 0);var Xj=m.p("yt.util.activity.getTimeSinceActive")||m.Le;m.l("yt.util.activity.getTimeSinceActive",Xj,void 0);
var Yj=m.p("yt.util.activity.setTimestamp")||Ke;m.l("yt.util.activity.setTimestamp",Yj,void 0);var Wh,ai;m.$h=null;ai="";var di=[];var ji,Ei,Di,ki,mi,ui,oi,qi,xi;ki=0;mi=[900,60,"waiting"];ui=[500,99,"waiting"];oi=[300,60,"waiting"];qi=[400,99,"waiting"];xi=[300,101,"done"];window.yt=window.yt||{};m.l("yt.setConfig",m.bb,void 0);m.l("yt.getConfig",m.x,void 0);m.l("yt.hasMsg",m.jb,void 0);m.l("yt.pubsub.publish",m.B,void 0);m.l("yt.pubsub.subscribe",m.z,void 0);m.l("yt.setMsg",function(a){cb(m.kb,arguments)},void 0);m.l("yt.setGoogMsg",function(a){cb(m.kb,arguments)},void 0);m.l("yt.timing.report",ee,void 0);
m.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=m.x("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);be(c)},void 0);m.l("ytcsi.tick",m.Md,void 0);m.t(Fi,m.zb);
Fi.prototype.enable=function(){window.onload=fi;window.onunload=gi;window.onerror=hi;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",ii),window.addEventListener("spfpartprocess",ni),window.addEventListener("spfpartdone",si),window.addEventListener("spfprocess",ti),window.addEventListener("spfdone",vi),window.addEventListener("spferror",yi),window.addEventListener("spfreload",zi),window.addEventListener("spfjsbeforeunload",Gi)),a.config=a.config||{},
window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",Ai),this.subscribe("dispose",Ci)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Fi.prototype.init=function(){Fi.D.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.x("PAGEFRAME_JS")?(b=m.x("PAGEFRAME_JS"),c=function(){window.ytPageFrameLoaded=!0;m.p("ytbin.www.pageframe.setup")()}):a&&(a=m.p("yt.www.masthead.loadSearchbox"))&&a();var a=m.x("JS_COMMON_MODULE"),d=m.x("JS_PAGE_MODULES");d||(d=[a]);a=m.x("JS_DELAY_LOAD",void 0);0<a?(m.gb(this.l),this.l=m.y(function(){b&&m.uc(b,c);window.spf.script.require(d)},a)):(b&&m.uc(b,
c),window.spf.script.require(d));Uh();m.l("yt.timing.ready_",!0,void 0);m.x("CSI_LOG_ON_TICK")&&Pd(!1);var a=!!m.p("yt.reactLoaded"),e=m.x("REACT_JS");!a&&e&&m.uc(e,function(){m.l("yt.reactLoaded",!0,void 0)})};Fi.prototype.dispose=function(){m.gb(this.l);var a=m.p("ytbin.www.pageframe.cancelSetup");a&&a();m.hb(Wh);if(a=m.Yh())a.removeEventListener("onReady",Xh),a.removeEventListener("onStateChange",Xh);m.l("yt.timing.ready_",!1,void 0);Fi.D.dispose.call(this)};
Fi.prototype.disable=function(){Fi.D.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",ii),window.removeEventListener("spfpartprocess",ni),window.removeEventListener("spfpartdone",si),window.removeEventListener("spfprocess",ti),window.removeEventListener("spfdone",vi),window.removeEventListener("spferror",yi),window.removeEventListener("spfreload",zi),window.removeEventListener("spfjsbeforeunload",Gi));window.onload=null;window.onunload=null;window.onerror=null};
m.Bb(new Fi);})(_yt_www);
