(function(){/*

SPF
(c) 2012-2014 Google, Inc.
License: MIT
*/
function l(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function n(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}function p(){return(new Date).getTime()}function ba(){};function ca(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function da(a,b){if(b){if(a.classList)return a.classList.contains(b);for(var c=ca(a),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0}return!1}function q(a,b){b&&(a.classList?a.classList.add(b):da(a,b)||(a.className+=" "+b))}function t(a,b){if(b)if(a.classList)a.classList.remove(b);else{for(var c=ca(a),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ")}};function u(a,b){return v[a]=b}var v=window._spf_state||{};window._spf_state=v;function w(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function ea(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function fa(a,b){if(a.filter)return a.filter(b,void 0);var c=[];w(a,function(a,e,f){b.call(void 0,a,e,f)&&c.push(a)});return c}
function ga(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;w(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function x(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};var ha={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},y={};"config"in v||u("config",y);y=v.config;function ia(a,b){var c=b||document;return c.querySelectorAll?c.querySelectorAll(a):[]}function ja(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}function ka(a,b,c){b=b||document;var d=b.createElement("iframe");d.id=a||"";d.src='javascript:""';d.style.display="none";c&&(d.onload=l(c,null,d));b.body.appendChild(d);return d};function la(a,b,c,d){var e=d||{},f=!1,g=0,k,h=new XMLHttpRequest;h.open(a,b,!0);h.timing={};var m=h.abort;h.abort=function(){clearTimeout(k);h.onreadystatechange=null;m.call(h)};h.onreadystatechange=function(){var a=h.timing;if(2==h.readyState){a.responseStart=a.responseStart||p();f=-1<(h.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked");if(!f){var a=h.getResponseHeader("X-Firefox-Spdy"),c=window.chrome&&chrome.loadTimes&&chrome.loadTimes(),c=c&&c.wasFetchedViaSpdy;f=!(!a&&
!c)}e.D&&e.D(h)}else 3==h.readyState?f&&e.n&&(a=h.responseText.substring(g),g=h.responseText.length,e.n(h,a)):4==h.readyState&&(a.responseEnd=a.responseEnd||p(),window.performance&&window.performance.getEntriesByName&&(h.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&e.n&&h.responseText.length>g&&(a=h.responseText.substring(g),g=h.responseText.length,e.n(h,a)),clearTimeout(k),e.C&&e.C(h))};a="POST"==a;if(e.headers)for(var z in e.headers)h.setRequestHeader(z,e.headers[z]),"content-type"==
z.toLowerCase()&&(a=!1);a&&h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.G&&(k=setTimeout(function(){h.abort();e.F&&e.F(h)},e.G));h.timing.fetchStart=p();h.send(c);return h};function A(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var na=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function B(a,b){var c=a.split(b),d=1==c.length;return[c[0],d?"":b,d?"":c.slice(1).join(b)]};function oa(a){var b=D();a in b&&delete b[a]}function pa(){var a=D(),b;for(b in a)qa(a[b])||delete a[b];a=D();b=parseInt(y["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e,f;for(f in a)a[f].count<d&&(e=f,d=a[f].count);delete a[e]}}function qa(a){if(!(a&&"data"in a))return!1;var b=a.life,b=isNaN(b)?Infinity:b;return p()-a.time<b}function ra(a){var b=parseInt(v["cache-counter"],10)||0;b++;u("cache-counter",b);a.count=b}
function D(a){return!a&&"cache-storage"in v?v["cache-storage"]:u("cache-storage",a||{})};function sa(a,b,c){var d=null,e=window.history.state;if(e){var d={},f;for(f in e)d[f]=e[f]}if(b)for(f in d=d||{},b)d[f]=b[f];ta(!0,a,d,c)}function ta(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=p();u("history-timestamp",e);c["spf-timestamp"]=e;if(a)ua(c,b);else if(a=va().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");u("history-url",b);d&&(d=v["history-callback"])&&d(b,c)}}
function wa(a){var b=window.location.href;if(v["history-ignore-pop"])u("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==v["history-url"]?(u("history-timestamp",c),ua(a,b)):(a["spf-back"]=c<parseInt(v["history-timestamp"],10),a["spf-current"]=v["history-url"],u("history-timestamp",c),u("history-url",b),(c=v["history-callback"])&&c(b,a))}}
function ua(a,b){var c=va().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function va(){var a=document.getElementById("history-iframe");a||(a=ka("history-iframe"));return a};function xa(a,b){a&&b&&(a in E||(E[a]=[]),E[a].push(b))}function ya(a,b){a in E&&b&&ea(E[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function za(a){a in E&&w(E[a],function(a,c,d){d[c]=null;a&&a()})}var E={};"ps-s"in v||u("ps-s",E);E=v["ps-s"];function F(a,b,c){var d=G[a];return a&&b?(d||(d=G[a]={items:[],l:0,j:0,p:1}),d.items.push({u:b,q:c||0})):d&&d.items.length||0}function H(a,b){var c=G[a];if(c){var d=!!c.l||!!c.j;0<c.p&&(b||!d)&&Aa(a,b)}}function I(a){(a=G[a])&&a.p--}function J(a,b){var c=G[a];c&&(c.p++,H(a,b))}function Ba(a){var b=G[a];b&&(Ca(b),delete G[a])}
function Aa(a,b){var c=G[a];if(c&&(Ca(c),0<c.p&&c.items.length)){var d=c.items[0];if(d){var e=l(function(a,b){b();a()},null,l(Aa,null,a,b));b?(c.items.shift(),e(d.u)):Da(c,d,e)}}}function Da(a,b,c){b.q?(c=l(c,null,ba),a.j=setTimeout(c,b.q),b.q=0):(a.items.shift(),c=l(c,null,b.u),(b=(b=y["advanced-task-scheduler"])&&b.addTask)?a.l=b(c):a.j=setTimeout(c,0))}function Ca(a){if(a.l){var b=y["advanced-task-scheduler"];(b=b&&b.cancelTask)&&b(a.l);a.l=0}a.j&&(clearTimeout(a.j),a.j=0)}var G={};function K(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,M:b.M,L:b.L};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function L(a,b){var c=K(a);return b?c.href:B(c.href,"#")[0]}
function Ea(a,b){var c=B(a,"#");a=c[0];for(var d=0;d<b.length;d++)a=a.replace(new RegExp("([?&])"+b[d]+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(a,b){return"?"==b?b:""});A(a,"?")&&(a=a.slice(0,-1));return a+c[1]+c[2]}function Fa(a){var b=y["advanced-persistent-parameters"]||"",c=B(a,"#");a=c[0];var d=-1!=a.indexOf("?")?"&":"?";return a+(b?d+b:"")+c[1]+c[2]};function Ga(a,b,c,d){var e="js"==a;b=M(a,b);var f=c||"^"+b,g=N(a,f),k;c&&(k=O(a,c))&&b!=k&&(n(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:c,url:k}),e=k,Ia(a,c),e&&Ja(a,e),e=N(a,c),delete E[e],xa(g,l(Ka,null,a,c,k)));e=N(a,b);if((e=P[e])&&f!=e){Ia(a,e);Ja(a,b);var h=N(a,e);h&&g&&h in E&&(E[g]=(E[g]||[]).concat(E[h]),delete E[h])}h=N(a,b);P[h]=f;La(a,f,b);xa(g,d);d=l(Ma,null,a);Q(a,b)?(e&&f!=e&&(a=Na(a,b))&&a.setAttribute("name",c||""),d()):(a=Oa(a,b,d,void 0,void 0,k))&&c&&a.setAttribute("name",
c)}function Pa(a,b){var c=O(a,b);Ia(a,b);c&&Ja(a,c);var d=N(a,b);delete E[d];Ka(a,b,c)}function Ka(a,b,c){c&&(n("js"==a?"spfjsunload":"spfcssunload",{name:b,url:c}),Qa(a,c))}function Ma(a){var b=N(a,""),c;for(c in E)0==c.indexOf(b)&&ea(c.substring(b.length).split("|"),l(Ra,null,a))&&za(c)}
function Oa(a,b,c,d,e,f){function g(){Q(a,b,e)&&Sa(2,a,b,e);k&&m&&m.parentNode&&h==document&&m.parentNode.removeChild(m);c&&setTimeout(c,0);return null}var k="js"==a;b=M(a,b);Sa(1,a,b,e);var h=d||document,m=h.createElement(k?"script":"link");if(!b)return g();d=R(b);m.className=N(a,d);"onload"in m?m.onerror=m.onload=g:m.onreadystatechange=function(){/^c|loade/.test(m.readyState)&&g()};d=h.getElementsByTagName("head")[0]||h.body;k?(m.async=!0,m.src=b,d.insertBefore(m,d.firstChild)):(m.rel="stylesheet",
m.href=b,(f=f&&Na(a,f,d))?d.insertBefore(m,f):d.appendChild(m));return m}function Qa(a,b){b=M(a,b);var c=Na(a,b,void 0);c&&c.parentNode&&c.parentNode.removeChild(c);c=N(a,b);delete S[c]}function Na(a,b,c){b=R(b);a="."+N(a,b);return ia(a,c)[0]}function Ta(a){var b="js"==a,c=[];w(ia(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href,e=M(a,e);if(!Q(a,e)){Sa(2,a,e);var f=R(e),f=N(a,f);q(d,f);if(f=d.getAttribute("name")){var g=N(a,e);P[g]=f;La(a,f,e)}c.push(d)}})}
function Ua(a,b){if(b&&(b=M(a,b),!Q(a,b))){var c=R(b),d=N(a,c),e=N(a,"prefetch"),c=document.getElementById(e);if(!c)c=ka(e,null,function(a){a.title=e;H(e,!0)});else if(c.contentWindow.document.getElementById(d))return;d=l(Va,null,c,a,b,d,e);c.title?d():F(e,d)}}
function Va(a,b,c,d,e){var f="css"==b;a=a.contentWindow.document;"js"==b?(b=a.createElement("object"),Wa?a.createElement("script").src=c:b.data=c,b.id=d,a.body.appendChild(b)):f?(b=Oa(b,c,null,a,e),b.id=d):(b=a.createElement("img"),b.src=c,b.id=d,a.body.appendChild(b))}
function Xa(a,b,c){for(var d="js"==a,e=O(a,c),f=b.replace(/\s/g,""),f=f||"",g=0,k=0,h=f.length;k<h;++k)g=31*g+f.charCodeAt(k),g%=4294967296;f="hash-"+g;La(a,c,f);!Ya(a,f)&&(b=Za(a,b))&&(Sa(2,a,f),b&&!d&&(d=R(f),d=N(a,d),b.className=d,b.setAttribute("name",c)),(e=e&&e[0])&&Qa(a,e))}
function Za(a,b){b=na(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body,d;"js"==a?(d=document.createElement("script"),d.text=b,c.appendChild(d),c.removeChild(d)):(d=document.createElement("style"),c.appendChild(d),"styleSheet"in d?d.styleSheet.cssText=b:d.appendChild(document.createTextNode(b)));return d}
function M(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=v[c]||"";if("[object String]"==Object.prototype.toString.call(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);b=0>b.indexOf("."+a)?b+"."+a:b;b=L(b)}else 0==d&&(b=L(b))}return b}function N(a,b,c){return a+"-"+b+(c?"-"+c:"")}function R(a){return a?String(a).replace(/[^\w]/g,""):""}function Sa(a,b,c,d){b=N(b,c,d);S[b]=a}function Q(a,b,c){a=N(a,b,c);return S[a]}
function Ya(a,b){var c=Q(a,b);return""==b||2==c}function Ja(a,b){var c=N(a,b);delete P[c]}function La(a,b,c){a=N(a,b);T[a]=c}function O(a,b){var c=N(a,b);return T[c]}function Ia(a,b){var c=N(a,b);delete T[c]}function Ra(a,b){var c=O(a,b);return void 0!=c&&Ya(a,c)}var S={},P={},T={},Wa=-1!=navigator.userAgent.indexOf(" Trident/");"rsrc-s"in v||u("rsrc-s",S);S=v["rsrc-s"];"rsrc-n"in v||u("rsrc-n",P);P=v["rsrc-n"];"rsrc-u"in v||u("rsrc-u",T);T=v["rsrc-u"];function $a(a){a=x(a);w(a,function(a){Ua("img",a)})};function ab(a,b,c){Ga("js",a,b,c)}function bb(a){Pa("js",a)}function cb(a,b){Oa("js",a,b)}function db(a){a=x(a);w(a,function(a){Ua("js",a)})}function eb(a,b,c){a=x(a);a=fa(a,function(a){return!!a});var d=[];w(a,function(a){void 0==O("js",a)&&d.push(a)});var e=!d.length;if(b){var f=ea(a,l(Ra,null,"js"));e&&f?b():(a=N("js",a.sort().join("|")),xa(a,b))}c&&!e&&c(d)}function fb(a,b){a=x(a);w(a,function(a){if(a){var b=gb[a]||a,b=M("js",b),e=O("js",a);e&&b!=e&&hb(a)}});eb(a,b,ib)}
function ib(a){w(a,function(a){function c(){ab(e,a)}var d=U[a],e=gb[a]||a;d?fb(d,c):c()})}function hb(a){a=x(a);w(a,function(a){var c=[],d;for(d in U){var e=U[d],e=x(e);w(e,function(e){e==a&&c.push(d)})}w(c,function(a){hb(a)});bb(a)})}function jb(a,b){Xa("js",a,b)}function kb(a){Za("js",a)}var U={};"js-d"in v||u("js-d",U);var U=v["js-d"],gb={};"js-u"in v||u("js-u",gb);gb=v["js-u"];function lb(a,b,c){Ga("css",a,b,c)}function mb(a,b){Oa("css",a,b)}function nb(a){a=x(a);w(a,function(a){Ua("css",a)})};function ob(a,b,c){if(b){var d=[],e;b=0;c&&(a+="\r\n");var f=a.indexOf("[\r\n",b);for(-1<f&&(b=f+3);-1<(f=a.indexOf(",\r\n",b));)e=na(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e));f=a.indexOf("]\r\n",b);-1<f&&(e=na(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e)));e="";a.length>b&&(e=a.substring(b),c&&A(e,"\r\n")&&(e=e.substring(0,e.length-2)));if(y["experimental-parse-extract"])for(a=0;a<d.length;a++)d[a]=pb(d[a]);return{k:d,e:e}}a=JSON.parse(a);"number"==typeof a.length?d=a:d=[a];if(y["experimental-parse-extract"])for(a=
0;a<d.length;a++)d[a]=pb(d[a]);return{k:d,e:""}}
function V(a,b,c,d){var e=c&&0==c.type.lastIndexOf("navigate",0),f=c&&c.reverse,g=c&&!!c.position,k=c&&c.g,h=b.name||"",m="process "+L(a),z=!y["experimental-process-async"],r;r=0;b.timing||(b.timing={});b.title&&(document.title=b.title);e&&b.url&&L(b.url)!=L(window.location.href)&&sa(b.url+window.location.hash);b.head&&(r=l(function(a,b){var c=W(a);qb(c);rb(c);I(m);sb(c,function(){b.spfProcessHead=p();J(m,z)})},null,b.head,b.timing),r=F(m,r));b.attr&&(r=l(function(a,b){for(var c in a){var d=document.getElementById(c);
if(d){var e=a[c],f=void 0;for(f in e){var g=e[f];"class"==f?d.className=g:"style"==f?d.style.cssText=g:d.setAttribute(f,g)}}}b.spfProcessAttr=p()},null,b.attr,b.timing),r=F(m,r));var C=b.body||{},pc=r,Ha;for(Ha in C)r=l(function(a,b){var d=document.getElementById(a);if(d){e&&!g&&!k&&y["experimental-scroll-position"]&&(u("nav-scroll-position",null),u("nav-scroll-url",null),window.scroll(0,0),k=!0,c&&(c.g=!0));var r=W(b);rb(r);var C=function(){I(m);sb(r,function(){J(m,z)})},ma=y["animation-class"];
tb&&da(d,ma)?(d=new ub(d,r.html,ma,h,!!f),I(m),H(d.key,!0),F(d.key,l(vb,null,d),0),F(d.key,l(wb,null,d),17),F(d.key,l(xb,null,d),d.K),F(d.key,l(function(){C();J(m,z)},null),0),H(d.key)):(ma=y["experimental-html-handler"])?(I(m),ma(r.html,d,function(){C();J(m,z)})):(d.innerHTML=r.html,C())}},null,Ha,C[Ha],b.timing),r=F(m,r);C=r-pc;b.foot?(r=l(function(a,b,c){c&&(b.spfProcessBody=p());a=W(a);rb(a);I(m);sb(a,function(){b.spfProcessFoot=p();J(m,z)})},null,b.foot,b.timing,C),r=F(m,r)):C&&(r=l(function(a){a.spfProcessBody=
p()},null,b.timing),r=F(m,r));d&&(r=F(m,l(d,null,a,b)));H(m,z)}function yb(a,b,c,d){c="preprocess "+L(a);var e;b.head&&(e=l(function(a){a=W(a);qb(a);zb(a);Ab(a)},null,b.head),F(c,e));var f=b.body||{},g;for(g in f)f[g]&&(e=l(function(a,b){var c=W(b);zb(c);Ab(c)},null,g,f[g]),F(c,e));b.foot&&(e=l(function(a){a=W(a);zb(a);Ab(a)},null,b.foot),F(c,e));d&&F(c,l(d,null,a,b));H(c)}
function vb(a){q(a.a,a.m);q(a.a,a.v);q(a.a,a.B);q(a.a,a.w);q(a.a,a.A);a.h=document.createElement("div");a.h.className=a.J;var b=a.a,c=a.h;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.d=document.createElement("div");a.d.className=a.I;a.d.innerHTML=a.H;a.reverse?(b=a.h,b.parentNode.insertBefore(a.d,b)):(b=a.h,b.parentNode.insertBefore(a.d,b.nextSibling))}function wb(a){t(a.a,a.w);t(a.a,a.A);q(a.a,a.s);q(a.a,a.t)}
function xb(a){a.a.removeChild(a.h);var b=a.d,c,d=b.parentNode;if(d&&11!=d.nodeType)if(b.removeNode)b.removeNode(!1);else{for(;c=b.firstChild;)d.insertBefore(c,b);d.removeChild(b)}t(a.a,a.s);t(a.a,a.t);t(a.a,a.v);t(a.a,a.B);t(a.a,a.m)}function pb(a){a.head&&(a.head=W(a.head));if(a.body)for(var b in a.body)a.body[b]=W(a.body[b]);a.foot&&(a.foot=W(a.foot));return a}
function W(a){var b=new Bb;if(!a)return b;if("[object String]"!=Object.prototype.toString.call(a))return a.scripts&&w(a.scripts,function(a){b.scripts.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&w(a.styles,function(a){b.styles.push({url:a.url||"",text:a.text||"",name:a.name||""})}),a.links&&y["experimental-preconnect"]&&w(a.links,function(a){"spf-preconnect"==a.rel&&b.links.push({url:a.url||"",rel:a.rel||""})}),b.html=a.html||"",b;a=a.replace(Cb,function(a,d,
e,f){return"script"==d?(a=(a=e.match(Db))?a[1]:"",d=(d=e.match(Eb))?d[1]:"",e=Fb.test(e),b.scripts.push({url:d,text:f,name:a,async:e}),""):"style"==d?(a=(a=e.match(Db))?a[1]:"",b.styles.push({url:"",text:f,name:a}),""):a});a=a.replace(Gb,function(a,d){var e=d.match(Hb),e=e?e[1]:"";if("stylesheet"==e){var e=(e=d.match(Db))?e[1]:"",f=d.match(Ib),f=f?f[1]:"";b.styles.push({url:f,text:"",name:e});return""}return"spf-preconnect"==e&&y["experimental-preconnect"]?(f=(f=d.match(Ib))?f[1]:"",b.links.push({url:f,
rel:e}),""):a});b.html=a;return b}function sb(a,b){if(0>=a.scripts.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.scripts.length){var e=a.scripts[c],f=function(){};e.url?f=e.name?l(ab,null,e.url,e.name):l(cb,null,e.url):e.text&&(f=e.name?l(jb,null,e.text,e.name):l(kb,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}function Ab(a){0>=a.scripts.length||(a=ga(a.scripts,function(a){return a.url}),db(a))}
function rb(a){if(!(0>=a.styles.length))for(var b=0,c=a.styles.length;b<c;b++){var d=a.styles[b];d.url?d.name?lb(d.url,d.name):mb(d.url):d.text&&(d.name?Xa("css",d.text,d.name):Za("css",d.text))}}function zb(a){0>=a.styles.length||(a=ga(a.styles,function(a){return a.url}),nb(a))}function qb(a){0>=a.links.length||(a=ga(a.links,function(a){return"spf-preconnect"==a.rel?a.url:""}),$a(a))}
function ub(a,b,c,d,e){var f=parseInt(y["animation-duration"],10);this.a=a;this.H=b;this.K=f;this.reverse=e;b=document.body;b=(b.dataset?b.dataset.spfName:b.getAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase()))||"";f=parseInt(v.uid,10)||0;f++;this.key=a["spf-key"]||(a["spf-key"]=""+u("uid",f));this.v=b&&c+"-from-"+b;this.B=d&&c+"-to-"+d;this.h=null;this.J=c+"-old";this.d=null;this.I=c+"-new";this.m=c+(e?"-reverse":"-forward");this.w=c+"-start";this.A=this.m+"-start";this.s=c+"-end";
this.t=this.m+"-end"}function Bb(){this.html="";this.scripts=[];this.styles=[];this.links=[]}
var tb=function(){var a=document.createElement("div");if("transition"in a.style)return!0;for(var b=["webkit","Moz","Ms","O","Khtml"],c=0,d=b.length;c<d;c++)if(b[c]+"Transition"in a.style)return!0;return!1}(),Gb=/\x3clink([\s\S]*?)\x3e/ig,Cb=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,Fb=/(?:\s|^)async(?:\s|=|$)/i,Ib=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,Db=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,Hb=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,Eb=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i;function Jb(a,b){var c=b||{};c.method=((c.method||"GET")+"").toUpperCase();c.type=c.type||"request";var d=a,e=y["url-identifier"]||"";if(e){var e=e.replace("__type__",c.type||""),f=B(d,"#"),g=B(f[0],"?"),d=g[0],k=g[1],g=g[2],h=f[1],f=f[2];if(0==e.lastIndexOf("?",0))k&&(e=e.replace("?","&")),g+=e;else{if(0==e.lastIndexOf(".",0))if(A(d,"/"))e="index"+e;else{var m=d.lastIndexOf(".");-1<m&&(d=d.substring(0,m))}else A(d,"/")&&0==e.lastIndexOf("/",0)&&(e=e.substring(1));d+=e}d=d+k+g+h+f}e=L(d);d={};d.spfUrl=
e;d.startTime=p();d.fetchStart=d.startTime;a:{g=Kb(a,c.current,null,c.type,!1);h=c.current;k=[];h&&(k.push(g+" previous "+h),k.push(g+" previous "+K(h).pathname));k.push(g);g=0;for(h=k.length;g<h;g++){b:{f=k[g];m=D();if(f in m){m=m[f];if(qa(m)){ra(m);f=m.data;break b}oa(f)}f=void 0}if(f){k={key:k[g],response:f.response,type:f.type};break a}}k=null}d.spfPrefetched=!!k&&"prefetch"==k.type;d.spfCached=!!k;if(k)return setTimeout(l(Lb,null,a,c,d,k.key,k.response),0),null;k={};void 0!=c.c&&(k["X-SPF-Referer"]=
c.c);c.current&&(k["X-SPF-Previous"]=c.current);if(g=y["advanced-header-identifier"])k["X-SPF-Request"]=g.replace("__type__",c.type),k.Accept="application/json";g=new Mb;d=l(Nb,null,a,c,d,g);d={headers:k,G:y["request-timeout"],D:l(Ob,null,a,g),n:l(Pb,null,a,c,g),C:d,F:d};return"POST"==c.method?la("POST",e,c.r,d):la("GET",e,null,d)}
function Lb(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=p();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,y["cache-unified"]||(oa(d),f=!0));if(b.f&&"multipart"==e.type){d=e.parts;for(var g=0;g<d.length;g++)b.f(a,d[g])}Qb(a,b,c,e,f)}function Ob(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.d=-1!=a.toLowerCase().indexOf("multipart")}
function Pb(a,b,c,d,e,f){if(c.d){e=c.e+e;var g;try{g=ob(e,!0,f)}catch(k){d.abort();b.i&&b.i(a,k);return}if(b.f)for(d=0;d<g.k.length;d++)b.f(a,g.k[d]);c.a=c.a.concat(g.k);c.e=g.e}}
function Nb(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var g in e.resourceTiming)c[g]=e.resourceTiming[g];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+e.resourceTiming.startTime>=c.startTime))for(var k in e.resourceTiming)g=e.resourceTiming[k],void 0!==g&&(A(k,"Start")||A(k,"End")||"startTime"==k)&&(c[k]=f+Math.round(g));"load"!=b.type&&(c.navigationStart=c.startTime);d.a.length&&
(d.e=na(d.e),d.e&&Pb(a,b,d,e,"",!0));var h;try{h=ob(e.responseText).k}catch(m){b.i&&b.i(a,m);return}if(b.f&&1<h.length)for(d=d.a.length;d<h.length;d++)b.f(a,h[d]);if(1<h.length){var z;d=0;for(e=h.length;d<e;d++)k=h[d],k.cacheType&&(z=k.cacheType);h={parts:h,type:"multipart"};z&&(h.cacheType=z)}else h=1==h.length?h[0]:{};Qb(a,b,c,h,!0)}
function Qb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=Kb(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},g=parseInt(y["cache-lifetime"],10),k=parseInt(y["cache-max"],10);0>=g||0>=k||(k=D(),f={data:f,life:g,time:p(),count:0},ra(f),k[e]=f,setTimeout(pa,1E3))}d.timing=c;b.o&&b.o(a,d)}
function Kb(a,b,c,d,e){a=L(a);var f;y["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+K(b).pathname);return f||""}function Mb(){this.d=!1;this.e="";this.a=[]};function Rb(a){return ja(a,function(a){return da(a,y["link-class"])})}function Sb(a){return ja(a,function(a){return da(a,y["nolink-class"])})}function Tb(a,b){return ja(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function Ub(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=Rb(a.target);return!b||y["nolink-class"]&&Sb(a.target)?null:(a=Tb(a.target,b))?a.href:null}function Vb(a){return K(a).origin!=K(window.location.href).origin?!1:!0}
function Wb(){if(!v["nav-init"])return!1;var a=parseInt(v["nav-counter"],10)||0;a++;var b=parseInt(y["navigate-limit"],10),b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(v["nav-init-time"],10);a--;a=p()-a;b=parseInt(y["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}function Xb(a){if(!a.defaultPrevented){var b=Ub(a);b&&(b=Fa(b),Vb(b)&&Wb()&&n("spfclick",{url:b,target:a.target})&&(Yb(b,{},new Zb),a.preventDefault()))}}function $b(a){var b=Ub(a);b&&setTimeout(function(){ac(b)},0)}
function bc(){var a;a=v["nav-scroll-position"]||null;var b=v["nav-scroll-url"]||"";a=a&&b==window.location.href?a:null;cc();a&&window.scroll.apply(null,a)}
function dc(a,b){var c=new Zb({current:b&&b["spf-current"],history:!0,position:b&&b["spf-position"],c:b&&b["spf-referer"],reverse:!(!b||!b["spf-back"])}),d=y["reload-identifier"];d&&(a=Ea(a,[d]));Vb(a)?Wb()?n("spfhistory",{url:a,referer:c.c,previous:c.current})&&(c.position&&y["experimental-scroll-position"]&&(u("nav-scroll-position",[window.pageXOffset,window.pageYOffset]),u("nav-scroll-url",window.location.href)),Yb(a,{},c)):X(a,"1"):X(a,"9")}
function Yb(a,b,c){ec();var d;a:{var e=c.current||window.location.href;if(-1!=a.indexOf("#")||-1!=e.indexOf("#"))if(d=L(a),e=L(e),d==e){d=!1;break a}d=!0}if(d)if(fc(a,c.c,c.current,b)){u("nav-counter",(parseInt(v["nav-counter"],10)||0)+1);gc(a);d=L(a);var e="preprocess "+L(d),f;for(f in G)e!=f&&0==f.lastIndexOf("preprocess",0)&&Ba(f);f=hc()[d];u("nav-request",f);u("nav-promote",null);u("nav-promote-time",null);f&&4!=f.readyState?(f="preprocess "+L(a),d="promote "+L(a),u("nav-promote",a),u("nav-promote-time",
p()),Ba(f),H(d,!0),c.history||ic(a,c.c,l(Y,null,b))):(f=l(Y,null,b),d=l(jc,null,b,c),e=l(kc,null,b,c),y["advanced-navigate-persist-timing"]||lc(),c.type="navigate",c.history&&(c.type+=c.reverse?"-back":"-forward"),b=Jb(a,{method:b.method,f:d,i:f,o:e,r:b.postData,type:c.type,current:c.current,c:c.c}),u("nav-request",b),c.history||ic(a,c.c,f))}else X(a,"2");else c.history||ic(a,c.c,l(Y,null,b)),mc(a,c)}
function mc(a,b){if(b.position)cc(),window.scroll.apply(null,b.position),b.g=!0;else{var c=B(a,"#");if(c[2]){if(c=document.getElementById(c[2]))cc(),c.scrollIntoView(),b.g=!0}else!b.g&&y["experimental-scroll-position"]&&(cc(),window.scroll(0,0),b.g=!0)}}function ic(a,b,c){try{sa(null,{"spf-position":[window.pageXOffset,window.pageYOffset]}),L(a,!0)!=window.location.href&&ta(!1,a,{"spf-referer":b},void 0)}catch(d){ec(),c(a,d)}}function Y(a,b,c){u("nav-request",null);nc(b,c,a)&&X(b,"10",c)}
function jc(a,b,c,d){if(oc(c,d,a))if(d.reload)X(c,"5");else if(d.redirect)qc(a,d.redirect);else try{V(c,d,b,function(){rc(c,d,a)})}catch(e){Y(a,c,e)}else X(c,"3")}
function kc(a,b,c,d){u("nav-request",null);if(v["nav-promote"]==b.b){var e=d.timing||{};e.navigationStart=v["nav-promote-time"];e.spfPrefetched=!0}var f="multipart"==d.type;if(!f){if(!sc(c,d,a)){X(c,"4");return}if(d.reload){X(c,"5");return}if(d.redirect){qc(a,d.redirect);return}}try{V(c,f?{}:d,b,function(){var e=d.name||"";if(f)for(var g=d.parts,m=0;m<g.length;m++)e=g[m].name||e;g=document.body;g.dataset?g.dataset.spfName=e:g.setAttribute("data-"+"spfName".replace(/([A-Z])/g,"-$1").toLowerCase(),
e);mc(c,b);tc(c,d,a)})}catch(g){Y(a,c,g)}}function qc(a,b){try{b+=window.location.hash,sa(b,null,!0)}catch(c){ec(),Y(a,b,c)}}function ec(){var a=v["nav-request"];a&&(a.abort(),u("nav-request",null))}function Z(a,b){var c;a&&(c=Array.prototype.slice.call(arguments),c[0]=a,c=aa.apply(null,c));return!1!==c}
function X(a,b,c){c=c?c.message:"";ec();gc();var d=b;c&&(d+=" Message: "+c);n("spfreload",{url:a,reason:d});y["experimental-remove-history"]&&window.location.href==a&&(u("history-ignore-pop",!0),window.history.back());setTimeout(function(){var c=y["reload-identifier"];if(c){var d={};d[c]=encodeURIComponent(b);var c=a,g=B(c,"#"),c=g[0],k=-1!=c.indexOf("?")?"&":"?",h;for(h in d)c+=k+h,d[h]&&(c+="="+d[h]),k="&";a=c+g[1]+g[2]}window.location.href=a},0)}
function uc(a,b,c){c.b=c.b||a;if(fc(a,void 0,void 0,b,!0)){var d=l(vc,null,!1,b,c),e=l(wc,null,!1,b,c),f=l(xc,null,!1,b,c);c.type="load";Jb(a,{method:b.method,f:e,i:d,o:f,r:b.postData,type:c.type})}}function ac(a,b){a=Fa(a);yc(a,b||{},new Zb)}function yc(a,b,c){c.b=c.b||a;if(fc(a,void 0,void 0,b,!0)){var d=l(vc,null,!0,b,c),e=l(wc,null,!0,b,c),f=l(xc,null,!0,b,c);c.type="prefetch";b=Jb(a,{method:b.method,f:e,i:d,o:f,r:b.postData,type:c.type,current:c.current});a=L(a);hc()[a]=b}}
function vc(a,b,c,d,e){a&&zc(d);a&&v["nav-promote"]==c.b?Y(b,d,e):nc(d,e,b,!0)}function wc(a,b,c,d,e){if(oc(d,e,b,!0)){if(e.reload){if(!a)return;if(v["nav-promote"]==c.b){X(d,"5");return}}if(e.redirect)Ac(a,b,c,e.redirect);else{if(a){var f=l(jc,null,b,c,d,e),g="promote "+L(c.b);F(g,f);if(v["nav-promote"]==c.b){H(g,!0);return}}(a?yb:V)(d,e,c,function(){rc(d,e,b,!0)})}}}
function xc(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!sc(d,e,b,!0)){X(d,"4");return}if(e.reload){if(!a)return;if(v["nav-promote"]==c.b){X(d,"5");return}}if(e.redirect){Ac(a,b,c,e.redirect);return}}var g="promote "+L(c.b);if(a){zc(d);if(v["nav-promote"]==c.b){F(g,l(kc,null,b,c,d,e));H(g,!0);return}Ba(g)}g=a?yb:V;try{g(d,f?{}:e,c,function(){tc(d,e,b,!0)})}catch(k){vc(a,b,c,d,k)}}
function Ac(a,b,c,d){a=a?yc:uc;var e={};w("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}function nc(a,b,c,d){a={url:a,err:b};(c=Z((c||{}).onError,a))&&!d&&(c=n("spferror",a));return c}function fc(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=Z((d||{}).onRequest,a))&&!e&&(d=n("spfrequest",a));return d}function oc(a,b,c,d){a={url:a,part:b};(c=Z((c||{}).onPartProcess,a))&&!d&&(c=n("spfpartprocess",a));return c}
function rc(a,b,c,d){a={url:a,part:b};Z((c||{}).onPartDone,a)&&!d&&n("spfpartdone",a)}function sc(a,b,c,d){a={url:a,response:b};(c=Z((c||{}).onProcess,a))&&!d&&(c=n("spfprocess",a));return c}function tc(a,b,c,d){a={url:a,response:b};Z((c||{}).onDone,a)&&!d&&n("spfdone",a)}function zc(a){a=L(a);var b=hc(),c=b[a];c&&c.abort();delete b[a]}function gc(a){var b=hc();a=a&&L(a);for(var c in b)a!=c&&zc(c)}
var lc,Bc=window.performance&&(window.performance.clearResourceTimings||window.performance.webkitClearResourceTimings||window.performance.mozClearResourceTimings||window.performance.msClearResourceTimings||window.performance.oClearResourceTimings);lc=Bc?l(Bc,window.performance):ba;function hc(){return"nav-prefetches"in v?v["nav-prefetches"]:u("nav-prefetches",{})}function cc(){u("nav-scroll-position",null);u("nav-scroll-url",null)}
function Zb(a){a=a||{};this.current=a.history&&a.current?a.current:window.location.href;this.history=!!a.history;this.b=a.b||"";this.position=a.position||null;this.c=void 0!=a.c?a.c:window.location.href;this.reverse=!!a.reverse;this.g=!!a.g;this.type=a.type||""};function Cc(){Ta("js");Ta("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Cc,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Cc))}document.addEventListener?document.addEventListener("DOMContentLoaded",Cc,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Cc);Cc();
var Dc={init:function(a){var b=!("function"!=typeof window.history.pushState&&!va().contentWindow.history.pushState);a=a||{};for(var c in ha)y[c]=c in a?a[c]:ha[c];for(c in a)c in ha||(y[c]=a[c]);if(b){c=nc;if(!v["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",wa,!1);u("history-init",!0);u("history-callback",dc);u("history-error-callback",c);u("history-listener",wa);u("history-url",a);u("history-timestamp",p());var d={"spf-referer":document.referrer};
try{sa(a,d)}catch(e){c&&c(a,e)}}!v["nav-init"]&&document.addEventListener&&(u("nav-init",!0),u("nav-init-time",p()),u("nav-counter",0),document.addEventListener("click",Xb,!1),u("nav-listener",Xb),!y["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",$b,!1),u("nav-mousedown-listener",$b)),y["experimental-scroll-position"]&&(document.addEventListener("scroll",bc,!1),u("nav-scroll-listener",
bc)))}return b},dispose:function(){"undefined"!=typeof History&&History.prototype.pushState&&(ec(),v["nav-init"]&&(document.removeEventListener&&(document.removeEventListener("click",v["nav-listener"],!1),document.removeEventListener("mousedown",v["nav-mousedown-listener"],!1),document.removeEventListener("scroll",v["nav-scroll-listener"],!1)),u("nav-listener",null),u("nav-mousedown-listener",null),u("nav-scroll-listener",null),u("nav-scroll-position",null),u("nav-scroll-url",null),u("nav-init",!1),
u("nav-init-time",null),u("nav-counter",null)),v["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",v["history-listener"],!1),u("history-init",!1),u("history-callback",null),u("history-error-callback",null),u("history-listener",null),u("history-url",null),u("history-timestamp",0)));for(var a in y)delete y[a]},navigate:function(a,b){a&&(a=Fa(a),Vb(a)?Wb()?Yb(a,b||{},new Zb):X(a,"1"):X(a,"9"))},load:function(a,b){a=Fa(a);uc(a,b||{},new Zb)},prefetch:ac,process:function(a,
b){function c(a,c,d,e){a==c&&b&&b(e)}var d=window.location.href;if("multipart"==a.type)for(var e=a.parts,f=0;f<e.length;f++){var g=l(c,null,f,e.length-1);V(d,e[f],null,g)}else g=l(c,null,0,0),V(d,a,null,g)}},Ec={cache:{remove:oa,clear:function(){D({})}},script:{load:ab,get:cb,ready:eb,done:function(a){La("js",a,"");Ma("js")},require:fb,declare:function(a,b){if(a){for(var c in a)U[c]=a[c];if(b)for(c in b)gb[c]=b[c]}},path:function(a){u("rsrc-p-js",a)},unload:bb,ignore:function(a,b){a=x(a);var c=N("js",
a.sort().join("|"));ya(c,b)},unrequire:hb,prefetch:db},style:{load:lb,get:mb,unload:function(a){Pa("css",a)},path:function(a){u("rsrc-p-css",a)},prefetch:nb}},Fc=this.spf=this.spf||{},Gc;for(Gc in Dc)Fc[Gc]=Dc[Gc];for(var Hc in Ec)for(var Ic in Ec[Hc])Fc[Hc]=Fc[Hc]||{},Fc[Hc][Ic]=Ec[Hc][Ic];n("spfready");})();
